In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
def get_all_icd_format(icd9,icd10):
    return [i for i in icd9] + [i.replace('.','') for i in icd9] + [i for i in icd9] + [i.replace('.','') for i in icd9] + [i for i in icd10] + [i.replace('.','') for i in icd10]

"""
cci
"""
def get_Myocardial_Infarction(x):
    pattern = r"410[0-9x]|412[0-9x]|I2[1-2][0-9x]|410[0-9x]|412[0-9x]"
    x = x.replace('.','')
    icd9 = ["410"]
    icd10 = ["I222", "I2121", "I2102", "I2111", "I213", "I229", "I214", "I2101", "I221", "I2129", "I2119", "I220", "I2109", "I228","I252"]
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False
    
def get_Congestive_heart_failure(x):
    pattern = r"428[0-9x]|428[0-9x]|I43[0-9x]|I50[0-9x]"
    x = x.replace('.','')
    icd9 = ['398.91', '402.01', '402.11', '402.91', '404.01', '404.03', '404.11', '404.13', '404.91', '404.93', '425.4', '425.5', '425.6', '425.7', '425.8', '425.9']
    icd10 = ['I09.9', 'I11.0', 'I13.0', 'I13.2', 'I25.5', 'I42.0', 'I42.5', 'I42.6', 'I42.7', 'I42.8', 'I42.9', 'P29.0']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False
    
def get_Peripheral_vascular_disease(x):
    pattern = r"44[0-1][0-9x]|44[0-1][0-9x]|I7[0-1][0-9x]"
    x = x.replace('.','')
    icd9 = ['443.9', '785.4', 'V43.4','093.0', '437.3', '443.1', '443.2', '443.3', '443.4', '443.5', '443.6', '443.7', '443.8', '443.9', '447.1', '557.1', '557.9', 'V43.4']
    icd10 = ['I73.1', 'I73.8', 'I73.9', 'I77.1', 'I79.0', 'I79.2', 'K55.1', 'K55.8', 'K55.9', 'Z95.8', 'Z95.9']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False   
    
def get_Cerebrovascular_disease(x):
    pattern = r"43[0-8][0-9x]|43[0-8][0-9x]|G4[5-6][0-9x]|I6[0-9][0-9x]"
    x = x.replace('.','')
    icd9 = ["362.34"]
    icd10 = ['H34.0']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False
            
def get_Dementia(x):
    pattern = r"290[0-9x]|290[0-9x]|F0[0-3][0-9x]|G30[0-9x]"
    x = x.replace('.','')
    icd9 = ["294.1","331.2"]
    icd10 = ['F05.1',"G31.1"]
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False
            
def get_Chronic_pulmonary_disease(x):
    pattern = r'49[0-9][0-9x]|50[0-5][0-9x]|49[0-9][0-9x]|50[0-5][0-9x]|J4[0-7][0-9x]|J6[0-7][0-9x]'
    x = x.replace('.','')
    icd9 = ["506.4","416.8","416.9","508.1","508.8"]
    icd10 = ['I27.8', 'I27.9' 'J68.4', 'J70.1', 'J70.3']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False
    
def get_Rheumatic_disease(x):
    pattern = r'714[0-2]|725[0-9x]|710[0-4]|714[0-2]|714[0-2]|725[0-9x]|710[0-4]|714[0-2]|M0[5-6][0-9x]|M3[2-4][0-9x]'
    x = x.replace('.','')
    icd9 = ["710.0","710.1","710.4","714.81","446.5","714.8"]
    icd10 = ['M31.5','M35.1','M35.3','M36.0']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False    
    
def get_Peptic_ulcer_disease(x):
    pattern = r'53[1-4][0-9x]|53[1-4][0-9x]|K2[5-8][0-9x]'
    x = x.replace('.','')
    icd9 = [""]
    icd10 = ['']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False     

def get_Mild_liver_disease(x):
    pattern = r'571[4-6]|57[0-1][0-9x]|571[4-6]|57[0-1][0-9x]|B18[0-9x]|K7[3-4][0-9x]'
    x = x.replace('.','')
    icd9 = ["571.2",'070.22', '070.23', '070.32', '070.33', '070.44', '070.54', '070.6', '070.9', '573.3', '573.4', '573.8', '573.9', 'V42.7']
    icd10 = ['K70.0', 'K70.1', 'K70.2', 'K70.3', 'K70.9', 'K71.3', 'K71.4', 'K71.5', 'K71.7','K76.0', 'K76.2', 'K76.3', 'K76.4', 'K76.8', 'K76.9', 'Z94.4']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False 
    
def get_Diabetes_without_chronic_complication(x):
    pattern = r'250[0-3]|250[7-9]|250[0-3]|250[7-9]'
    x = x.replace('.','')
    icd9 = ['']
    icd10 = ['E10.0', 'E10.1', 'E10.6', 'E10.8', 'E10.9', 'E11.0', 'E11.1', 'E11.6', 'E11.8', 'E11.9', 'E12.0', 'E12.1', 'E12.6', 'E12.8', 'E12.9', 'E13.0', 'E13.1', 'E13.6', 'E13.8', 'E13.9', 'E14.0', 'E14.1', 'E14.6', 'E14.8', 'E14.9']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False
    
def get_Diabetes_with_chronic_complication(x):
    pattern = r'250[4-6]|250[4-6]'
    x = x.replace('.','')
    icd9 = ['']
    icd10 = ['E10.2', 'E10.3', 'E10.4', 'E10.5', 'E10.7', 'E11.2', 'E11.3', 'E11.4', 'E11.5', 'E11.7', 'E12.2', 'E12.3', 'E12.4', 'E12.5', 'E12.7', 'E13.2', 'E13.3', 'E13.4', 'E13.5', 'E13.7', 'E14.2', 'E14.3', 'E14.4', 'E14.5', 'E14.7']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False
    
def get_Hemiplegia_or_paraplegia(x):
    pattern = r'34[2-3][0-9x]|344[0-6]|34[2-3][0-9x]|344[0-6]|G8[1-2][0-9x]'
    x = x.replace('.','')
    icd9 = ['344.1','344.9']
    icd10 = ['G04.1', 'G11.4', 'G80.1', 'G80.2', 'G83.0', 'G83.1', 'G83.2', 'G83.3', 'G83.4', 'G83.9']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False    
    
def get_Renal_disease(x):
    pattern = r'582[0-9x]|58[5-6][0-9x]|588[0-9x]|583[0-7]|V56[0-9x]|582[0-9x]|58[5-6][0-9x]|588[0-9x]|583[0-7]|V56[0-9x]|N1[8-9][0-9x]'
    x = x.replace('.','')
    icd9 = ['403.01', '403.11', '403.91', '404.02', '404.03', '404.12', '404.13', '404.92', '404.93', 'V42.0', 'V45.1']
    icd10 = ['I12.0', 'I13.1', 'N03.2', 'N03.3', 'N03.4', 'N03.5', 'N03.6', 'N03.7', 'N05.2', 'N05.3', 'N05.4', 'N05.5', 'N05.6', 'N05.7', 'N25.0', 'Z49.0', 'Z49.1', 'Z49.2', 'Z94.0', 'Z99.2']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False 
    
def get_Cancer(x):
    pattern = r'1[4-6][0-9][0-9x]|17[0-2][0-9x]|17[4-9][0-9x]|18[0-9][0-9x]|19[0-4][0-9x]|195[0-8x]|20[0-8][0-9x]|1[4-6][0-9][0-9x]|17[0-2][0-9x]|17[4-9][0-9x]|18[0-9][0-9x]|19[0-4][0-9x]|195[0-8x]|20[0-8][0-9x]|C[0-1][0-9][0-9x]|C2[0-6][0-9x]|C3[0-4][0-9x]|C3[7-9][0-9x]|C4[0-1][0-9x]|C43[0-9x]|C4[5-9][0-9x]|C5[0-8][0-9x]|C6[0-9][0-9x]|C7[0-6][0-9x]|C8[1-5][0-9x]|C88[0-9x]|C9[0-7][0-9x]'
    x = x.replace('.','')
    icd9 = ['238.6']
    icd10 = ['']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False   
    
def get_Moderate_or_severe_liver_disease(x):
    pattern = r"456[0-9]|456[0-1][0-9]|572[2-8]|456[0-2]|456[0-9]|456[0-1][0-9]|572[2-8]|456[0-2]"
    x = x.replace('.','')
    icd9 = ['456.20','456.21']
    icd10 = ['I85.0', 'I85.9', 'I86.4', 'I98.2', 'K70.4', 'K71.1', 'K72.1', 'K72.9', 'K76.5', 'K76.6', 'K76.7']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False 
    
def get_Metastatic_solid_tumor(x):
    pattern = r'19[6-9][0-9x]|19[6-9][0-9x]|C7[7-9][0-9x]|C80[0-9x]'
    x = x.replace('.','')
    icd9 = ['']
    icd10 = ['']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False 
    
def get_AIDS_HIV(x):
    pattern = r'04[2-4][0-9x]|04[2-4][0-9x]|B2[0-2][0-9x]|B24[0-9x]'
    x = x.replace('.','')
    icd9 = ['']
    icd10 = ['']
    icd_list = get_all_icd_format(icd9,icd10)
    if x in icd_list:
        return True
    elif re.match(pattern,x):
        return True
    else:
        return False

In [48]:
obesity_icd = ['ICD10-D:O99840','ICD10-D:O99841','ICD10-D:O99842','ICD10-D:O99843','ICD10-D:O99844','ICD10-D:O99845','ICD10-D:Z9884','ICD10-D:Z6825','ICD10-D:Z6826','ICD10-D:Z6827','ICD10-D:Z6828','ICD10-D:Z6829','ICD10-D:Z6830','ICD10-D:Z6831','ICD10-D:Z6832','ICD10-D:Z6833','ICD10-D:Z6834','ICD10-D:Z6835','ICD10-D:Z6836','ICD10-D:Z6837','ICD10-D:Z6838','ICD10-D:Z6839','ICD10-D:Z6841','ICD10-D:Z6842','ICD10-D:Z6843','ICD10-D:Z6844','ICD10-D:Z6845','ICD10-D:E6601','ICD10-D:E6609','ICD10-D:E661','ICD10-D:E662','ICD10-D:E668','ICD10-D:E669','ICD10-D:O99210','ICD10-D:O99211','ICD10-D:O99212','ICD10-D:O99213','ICD10-D:O99214','ICD10-D:O99215','ICD10-D:E663','ICD10-D:O2600','ICD10-D:O2601','ICD10-D:O2602','ICD10-D:O2603','ICD9-D:V4586','ICD9-D:64923','ICD9-D:64922','ICD9-D:64921','ICD9-D:64924','ICD9-D:64920','ICD9-D:53989','ICD9-D:V8521','ICD9-D:V8522','ICD9-D:V8523','ICD9-D:V8524','ICD9-D:V8525','ICD9-D:V8530','ICD9-D:V8531','ICD9-D:V8532','ICD9-D:V8533','ICD9-D:V8534','ICD9-D:V8535','ICD9-D:V8536','ICD9-D:V8537','ICD9-D:V8538','ICD9-D:V8539','ICD9-D:V8541','ICD9-D:V8542','ICD9-D:V8543','ICD9-D:V8544','ICD9-D:V8545','ICD9-D:V691','ICD9-D:2781','ICD9-D:27801','ICD9-D:64913','ICD9-D:64912','ICD9-D:64911','ICD9-D:64914','ICD9-D:64910','ICD9-D:27803','ICD9-D:27800','ICD9-D:27802','ICD9-D:7831','ICD9-D:64613','ICD9-D:64612','ICD9-D:64611','ICD9-D:64614','ICD9-D:64610']
diabetes_icd = ['ICD10-D:Z8632','ICD10-D:E0800','ICD10-D:E0801','ICD10-D:E0810','ICD10-D:E0811','ICD10-D:E0821','ICD10-D:E0822','ICD10-D:E0829','ICD10-D:E08311','ICD10-D:E08319','ICD10-D:E083211','ICD10-D:E083212','ICD10-D:E083213','ICD10-D:E083219','ICD10-D:E083291','ICD10-D:E083292','ICD10-D:E083293','ICD10-D:E083299','ICD10-D:E083311','ICD10-D:E083312','ICD10-D:E083313','ICD10-D:E083319','ICD10-D:E083391','ICD10-D:E083392','ICD10-D:E083393','ICD10-D:E083399','ICD10-D:E083411','ICD10-D:E083412','ICD10-D:E083413','ICD10-D:E083419','ICD10-D:E083491','ICD10-D:E083492','ICD10-D:E083493','ICD10-D:E083499','ICD10-D:E083511','ICD10-D:E083512','ICD10-D:E083513','ICD10-D:E083519','ICD10-D:E083521','ICD10-D:E083522','ICD10-D:E083523','ICD10-D:E083529','ICD10-D:E083531','ICD10-D:E083532','ICD10-D:E083533','ICD10-D:E083539','ICD10-D:E083541','ICD10-D:E083542','ICD10-D:E083543','ICD10-D:E083549','ICD10-D:E083551','ICD10-D:E083552','ICD10-D:E083553','ICD10-D:E083559','ICD10-D:E083591','ICD10-D:E083592','ICD10-D:E083593','ICD10-D:E083599','ICD10-D:E0836','ICD10-D:E0837X1','ICD10-D:E0837X2','ICD10-D:E0837X3','ICD10-D:E0837X9','ICD10-D:E0839','ICD10-D:E0840','ICD10-D:E0841','ICD10-D:E0842','ICD10-D:E0843','ICD10-D:E0844','ICD10-D:E0849','ICD10-D:E0851','ICD10-D:E0852','ICD10-D:E0859','ICD10-D:E08610','ICD10-D:E08618','ICD10-D:E08620','ICD10-D:E08621','ICD10-D:E08622','ICD10-D:E08628','ICD10-D:E08630','ICD10-D:E08638','ICD10-D:E08641','ICD10-D:E08649','ICD10-D:E0865','ICD10-D:E0869','ICD10-D:E088','ICD10-D:E089','ICD10-D:E0900','ICD10-D:E0901','ICD10-D:E0910','ICD10-D:E0911','ICD10-D:E0921','ICD10-D:E0922','ICD10-D:E0929','ICD10-D:E09311','ICD10-D:E09319','ICD10-D:E093211','ICD10-D:E093212','ICD10-D:E093213','ICD10-D:E093219','ICD10-D:E093291','ICD10-D:E093292','ICD10-D:E093293','ICD10-D:E093299','ICD10-D:E093311','ICD10-D:E093312','ICD10-D:E093313','ICD10-D:E093319','ICD10-D:E093391','ICD10-D:E093392','ICD10-D:E093393','ICD10-D:E093399','ICD10-D:E093411','ICD10-D:E093412','ICD10-D:E093413','ICD10-D:E093419','ICD10-D:E093491','ICD10-D:E093492','ICD10-D:E093493','ICD10-D:E093499','ICD10-D:E093511','ICD10-D:E093512','ICD10-D:E093513','ICD10-D:E093519','ICD10-D:E093521','ICD10-D:E093522','ICD10-D:E093523','ICD10-D:E093529','ICD10-D:E093531','ICD10-D:E093532','ICD10-D:E093533','ICD10-D:E093539','ICD10-D:E093541','ICD10-D:E093542','ICD10-D:E093543','ICD10-D:E093549','ICD10-D:E093551','ICD10-D:E093552','ICD10-D:E093553','ICD10-D:E093559','ICD10-D:E093591','ICD10-D:E093592','ICD10-D:E093593','ICD10-D:E093599','ICD10-D:E0936','ICD10-D:E0937X1','ICD10-D:E0937X2','ICD10-D:E0937X3','ICD10-D:E0937X9','ICD10-D:E0939','ICD10-D:E0940','ICD10-D:E0941','ICD10-D:E0942','ICD10-D:E0943','ICD10-D:E0944','ICD10-D:E0949','ICD10-D:E0951','ICD10-D:E0952','ICD10-D:E0959','ICD10-D:E09610','ICD10-D:E09618','ICD10-D:E09620','ICD10-D:E09621','ICD10-D:E09622','ICD10-D:E09628','ICD10-D:E09630','ICD10-D:E09638','ICD10-D:E09641','ICD10-D:E09649','ICD10-D:E0965','ICD10-D:E0969','ICD10-D:E098','ICD10-D:E099','ICD10-D:E1010','ICD10-D:E1011','ICD10-D:E1021','ICD10-D:E1022','ICD10-D:E1029','ICD10-D:E10311','ICD10-D:E10319','ICD10-D:E103211','ICD10-D:E103212','ICD10-D:E103213','ICD10-D:E103219','ICD10-D:E103291','ICD10-D:E103292','ICD10-D:E103293','ICD10-D:E103299','ICD10-D:E103311','ICD10-D:E103312','ICD10-D:E103313','ICD10-D:E103319','ICD10-D:E103391','ICD10-D:E103392','ICD10-D:E103393','ICD10-D:E103399','ICD10-D:E103411','ICD10-D:E103412','ICD10-D:E103413','ICD10-D:E103419','ICD10-D:E103491','ICD10-D:E103492','ICD10-D:E103493','ICD10-D:E103499','ICD10-D:E103511','ICD10-D:E103512','ICD10-D:E103513','ICD10-D:E103519','ICD10-D:E103521','ICD10-D:E103522','ICD10-D:E103523','ICD10-D:E103529','ICD10-D:E103531','ICD10-D:E103532','ICD10-D:E103533','ICD10-D:E103539','ICD10-D:E103541','ICD10-D:E103542','ICD10-D:E103543','ICD10-D:E103549','ICD10-D:E103551','ICD10-D:E103552','ICD10-D:E103553','ICD10-D:E103559','ICD10-D:E103591','ICD10-D:E103592','ICD10-D:E103593','ICD10-D:E103599','ICD10-D:E1036','ICD10-D:E1037X1','ICD10-D:E1037X2','ICD10-D:E1037X3','ICD10-D:E1037X9','ICD10-D:E1039','ICD10-D:E1040','ICD10-D:E1041','ICD10-D:E1042','ICD10-D:E1043','ICD10-D:E1044','ICD10-D:E1049','ICD10-D:E1051','ICD10-D:E1052','ICD10-D:E1059','ICD10-D:E10610','ICD10-D:E10618','ICD10-D:E10620','ICD10-D:E10621','ICD10-D:E10622','ICD10-D:E10628','ICD10-D:E10630','ICD10-D:E10638','ICD10-D:E10641','ICD10-D:E10649','ICD10-D:E1065','ICD10-D:E1069','ICD10-D:E108','ICD10-D:E109','ICD10-D:E1100','ICD10-D:E1101','ICD10-D:E1110','ICD10-D:E1111','ICD10-D:E1121','ICD10-D:E1122','ICD10-D:E1129','ICD10-D:E11311','ICD10-D:E11319','ICD10-D:E113211','ICD10-D:E113212','ICD10-D:E113213','ICD10-D:E113219','ICD10-D:E113291','ICD10-D:E113292','ICD10-D:E113293','ICD10-D:E113299','ICD10-D:E113311','ICD10-D:E113312','ICD10-D:E113313','ICD10-D:E113319','ICD10-D:E113391','ICD10-D:E113392','ICD10-D:E113393','ICD10-D:E113399','ICD10-D:E113411','ICD10-D:E113412','ICD10-D:E113413','ICD10-D:E113419','ICD10-D:E113491','ICD10-D:E113492','ICD10-D:E113493','ICD10-D:E113499','ICD10-D:E113511','ICD10-D:E113512','ICD10-D:E113513','ICD10-D:E113519','ICD10-D:E113521','ICD10-D:E113522','ICD10-D:E113523','ICD10-D:E113529','ICD10-D:E113531','ICD10-D:E113532','ICD10-D:E113533','ICD10-D:E113539','ICD10-D:E113541','ICD10-D:E113542','ICD10-D:E113543','ICD10-D:E113549','ICD10-D:E113551','ICD10-D:E113552','ICD10-D:E113553','ICD10-D:E113559','ICD10-D:E113591','ICD10-D:E113592','ICD10-D:E113593','ICD10-D:E113599','ICD10-D:E1136','ICD10-D:E1137X1','ICD10-D:E1137X2','ICD10-D:E1137X3','ICD10-D:E1137X9','ICD10-D:E1139','ICD10-D:E1140','ICD10-D:E1141','ICD10-D:E1142','ICD10-D:E1143','ICD10-D:E1144','ICD10-D:E1149','ICD10-D:E1151','ICD10-D:E1152','ICD10-D:E1159','ICD10-D:E11610','ICD10-D:E11618','ICD10-D:E11620','ICD10-D:E11621','ICD10-D:E11622','ICD10-D:E11628','ICD10-D:E11630','ICD10-D:E11638','ICD10-D:E11641','ICD10-D:E11649','ICD10-D:E1165','ICD10-D:E1169','ICD10-D:E118','ICD10-D:E119','ICD10-D:E1300','ICD10-D:E1301','ICD10-D:E1310','ICD10-D:E1311','ICD10-D:E1321','ICD10-D:E1322','ICD10-D:E1329','ICD10-D:E13311','ICD10-D:E13319','ICD10-D:E133211','ICD10-D:E133212','ICD10-D:E133213','ICD10-D:E133219','ICD10-D:E133291','ICD10-D:E133292','ICD10-D:E133293','ICD10-D:E133299','ICD10-D:E133311','ICD10-D:E133312','ICD10-D:E133313','ICD10-D:E133319','ICD10-D:E133391','ICD10-D:E133392','ICD10-D:E133393','ICD10-D:E133399','ICD10-D:E133411','ICD10-D:E133412','ICD10-D:E133413','ICD10-D:E133419','ICD10-D:E133491','ICD10-D:E133492','ICD10-D:E133493','ICD10-D:E133499','ICD10-D:E133511','ICD10-D:E133512','ICD10-D:E133513','ICD10-D:E133519','ICD10-D:E133521','ICD10-D:E133522','ICD10-D:E133523','ICD10-D:E133529','ICD10-D:E133531','ICD10-D:E133532','ICD10-D:E133533','ICD10-D:E133539','ICD10-D:E133541','ICD10-D:E133542','ICD10-D:E133543','ICD10-D:E133549','ICD10-D:E133551','ICD10-D:E133552','ICD10-D:E133553','ICD10-D:E133559','ICD10-D:E133591','ICD10-D:E133592','ICD10-D:E133593','ICD10-D:E133599','ICD10-D:E1336','ICD10-D:E1337X1','ICD10-D:E1337X2','ICD10-D:E1337X3','ICD10-D:E1337X9','ICD10-D:E1339','ICD10-D:E1340','ICD10-D:E1341','ICD10-D:E1342','ICD10-D:E1343','ICD10-D:E1344','ICD10-D:E1349','ICD10-D:E1351','ICD10-D:E1352','ICD10-D:E1359','ICD10-D:E13610','ICD10-D:E13618','ICD10-D:E13620','ICD10-D:E13621','ICD10-D:E13622','ICD10-D:E13628','ICD10-D:E13630','ICD10-D:E13638','ICD10-D:E13641','ICD10-D:E13649','ICD10-D:E1365','ICD10-D:E1369','ICD10-D:E138','ICD10-D:E139','ICD10-D:O24011','ICD10-D:O24012','ICD10-D:O24013','ICD10-D:O24019','ICD10-D:O2402','ICD10-D:O2403','ICD10-D:O24111','ICD10-D:O24112','ICD10-D:O24113','ICD10-D:O24119','ICD10-D:O2412','ICD10-D:O2413','ICD10-D:O24311','ICD10-D:O24312','ICD10-D:O24313','ICD10-D:O24319','ICD10-D:O2432','ICD10-D:O2433','ICD10-D:O24811','ICD10-D:O24812','ICD10-D:O24813','ICD10-D:O24819','ICD10-D:O2482','ICD10-D:O2483','ICD10-D:O24911','ICD10-D:O24912','ICD10-D:O24913','ICD10-D:O24919','ICD10-D:O2492','ICD10-D:R7303','ICD10-D:O24410','ICD10-D:O24414','ICD10-D:O24415','ICD10-D:O24419','ICD10-D:O24420','ICD10-D:O24424','ICD10-D:O24425','ICD10-D:O24429','ICD10-D:O24430','ICD10-D:O24434','ICD10-D:O24435','ICD10-D:O24439','ICD10-D:P700','ICD10-D:Z8632','ICD10-D:E891','ICD10-D:Z794','ICD10-D:T85614A','ICD10-D:T85614D','ICD10-D:T85614S','ICD10-D:T85624A','ICD10-D:T85624D','ICD10-D:T85624S','ICD10-D:T85633A','ICD10-D:T85633D','ICD10-D:T85633S','ICD10-D:T85694A','ICD10-D:T85694D','ICD10-D:T85694S','ICD10-D:T8572XA','ICD10-D:T8572XD','ICD10-D:T8572XS','ICD10-D:Z4681','ICD10-D:Z9641','ICD9-D:64803','ICD9-D:64802','ICD9-D:64801','ICD9-D:64804','ICD9-D:64800','ICD9-D:25001','ICD9-D:25003','ICD9-D:25000','ICD9-D:25002','ICD9-D:25021','ICD9-D:25023','ICD9-D:25020','ICD9-D:25022','ICD9-D:25011','ICD9-D:25013','ICD9-D:25010','ICD9-D:25012','ICD9-D:25061','ICD9-D:25063','ICD9-D:25060','ICD9-D:25062','ICD9-D:25051','ICD9-D:25053','ICD9-D:25050','ICD9-D:25052','ICD9-D:25031','ICD9-D:25033','ICD9-D:25030','ICD9-D:25032','ICD9-D:25081','ICD9-D:25083','ICD9-D:25080','ICD9-D:25082','ICD9-D:25071','ICD9-D:25073','ICD9-D:25070','ICD9-D:25072','ICD9-D:25041','ICD9-D:25043','ICD9-D:25040','ICD9-D:25042','ICD9-D:25091','ICD9-D:25093','ICD9-D:25090','ICD9-D:25092','ICD9-D:36207','ICD9-D:5881','ICD9-D:V1221','ICD9-D:3572','ICD9-D:3572','ICD9-D:24921','ICD9-D:24910','ICD9-D:24911','ICD9-D:24960','ICD9-D:24961','ICD9-D:24950','ICD9-D:24951','ICD9-D:24930','ICD9-D:24931','ICD9-D:24980','ICD9-D:24981','ICD9-D:24970','ICD9-D:24971','ICD9-D:24940','ICD9-D:24941','ICD9-D:24990','ICD9-D:24991','ICD9-D:24900','ICD9-D:24901','ICD9-D:V6546','ICD9-D:V5391','ICD9-D:V4585','ICD9-D:E9323','ICD9-D:V5867','ICD9-D:99657','ICD9-D:2513','ICD9-D:99523']
hld_icd = ['ICD10-D:Z8342','ICD10-D:E782','ICD10-D:E7849','ICD10-D:E785','ICD10-D:E755','ICD10-D:E7529','ICD10-D:E753','ICD10-D:E7511','ICD9-D:2720','ICD9-D:2722','ICD9-D:2724','ICD9-D:2727','ICD9-D:3301','ICD9-D:3302']
htn_icd = ['ICD10-D:H35031','ICD10-D:H35032','ICD10-D:H35033','ICD10-D:H35039','ICD10-D:I10','ICD10-D:I110','ICD10-D:I119','ICD10-D:I120','ICD10-D:I129','ICD10-D:I130','ICD10-D:I1310','ICD10-D:I1311','ICD10-D:I132','ICD10-D:I150','ICD10-D:I151','ICD10-D:I152','ICD10-D:I158','ICD10-D:I159','ICD10-D:I160','ICD10-D:I161','ICD10-D:I169','ICD10-D:I674','ICD10-D:I87301','ICD10-D:I87302','ICD10-D:I87303','ICD10-D:I87309','ICD10-D:I87311','ICD10-D:I87312','ICD10-D:I87313','ICD10-D:I87319','ICD10-D:I87321','ICD10-D:I87322','ICD10-D:I87323','ICD10-D:I87329','ICD10-D:I87331','ICD10-D:I87332','ICD10-D:I87333','ICD10-D:I87339','ICD10-D:I87391','ICD10-D:I87392','ICD10-D:I87393','ICD10-D:I87399','ICD10-D:I973','ICD10-D:O10011','ICD10-D:O10012','ICD10-D:O10013','ICD10-D:O10019','ICD10-D:O1002','ICD10-D:O1003','ICD10-D:O10111','ICD10-D:O10112','ICD10-D:O10113','ICD10-D:O10119','ICD10-D:O1012','ICD10-D:O1013','ICD10-D:O10211','ICD10-D:O10212','ICD10-D:O10213','ICD10-D:O10219','ICD10-D:O1022','ICD10-D:O1023','ICD10-D:O10311','ICD10-D:O10312','ICD10-D:O10313','ICD10-D:O10319','ICD10-D:O1032','ICD10-D:O1033','ICD10-D:O10411','ICD10-D:O10412','ICD10-D:O10413','ICD10-D:O10419','ICD10-D:O1042','ICD10-D:O1043','ICD10-D:O10911','ICD10-D:O10912','ICD10-D:O10913','ICD10-D:O10919','ICD10-D:O1092','ICD10-D:O1093','ICD10-D:O111','ICD10-D:O112','ICD10-D:O113','ICD10-D:O114','ICD10-D:O115','ICD10-D:O119','ICD9-D:4011','ICD9-D:64203','ICD9-D:64201','ICD9-D:64204','ICD9-D:64200','ICD9-D:64202','ICD9-D:40211','ICD9-D:40210','ICD9-D:40511','ICD9-D:45932','ICD9-D:45939','ICD9-D:45931','ICD9-D:45933','ICD9-D:45930','ICD9-D:99791','ICD9-D:7962','ICD9-D:64213','ICD9-D:64212','ICD9-D:64211','ICD9-D:64214','ICD9-D:64210','ICD9-D:40310','ICD9-D:40311','ICD9-D:40300','ICD9-D:40301','ICD9-D:40390','ICD9-D:40391','ICD9-D:40413','ICD9-D:40411','ICD9-D:40410','ICD9-D:40412','ICD9-D:40401','ICD9-D:40403','ICD9-D:40400','ICD9-D:40402','ICD9-D:40493','ICD9-D:40491','ICD9-D:40490','ICD9-D:40492','ICD9-D:4010','ICD9-D:40201','ICD9-D:40200','ICD9-D:40501','ICD9-D:40519','ICD9-D:40509','ICD9-D:64220','ICD9-D:64223','ICD9-D:64222','ICD9-D:64221','ICD9-D:64224','ICD9-D:64273','ICD9-D:64272','ICD9-D:64271','ICD9-D:64274','ICD9-D:64270','ICD9-D:64233','ICD9-D:64231','ICD9-D:64232','ICD9-D:64234','ICD9-D:64230','ICD9-D:4019','ICD9-D:64293','ICD9-D:64292','ICD9-D:64291','ICD9-D:64294','ICD9-D:64290','ICD9-D:40291','ICD9-D:40290','ICD9-D:40591']
heartD_icd = ['ICD10-D:I253','ICD10-D:I2541','ICD10-D:I671','ICD10-D:I711','ICD10-D:I712','ICD10-D:I713','ICD10-D:I714','ICD10-D:I715','ICD10-D:I716','ICD10-D:I718','ICD10-D:I719','ICD10-D:I720','ICD10-D:Q2543','ICD10-D:I200',
              'ICD10-D:I201','ICD10-D:I208','ICD10-D:I209','ICD10-D:I237','ICD10-D:I498','ICD10-D:I499','ICD10-D:I2510','ICD10-D:I25110','ICD10-D:I25111','ICD10-D:I25118','ICD10-D:I25119','ICD10-D:I25700','ICD10-D:I25701',
              'ICD10-D:I25708','ICD10-D:I25709','ICD10-D:I25710','ICD10-D:I25711','ICD10-D:I25718','ICD10-D:I25719','ICD10-D:I25720','ICD10-D:I25721','ICD10-D:I25728','ICD10-D:I25729','ICD10-D:I25730','ICD10-D:I25731',
              'ICD10-D:I25738','ICD10-D:I25739','ICD10-D:I25750','ICD10-D:I25751','ICD10-D:I25758','ICD10-D:I25759','ICD10-D:I25760','ICD10-D:I25761','ICD10-D:I25768','ICD10-D:I25769','ICD10-D:I25790','ICD10-D:I25791',
              'ICD10-D:I25798','ICD10-D:I25799','ICD10-D:I25810','ICD10-D:I25811','ICD10-D:I25812','ICD10-D:I2582','ICD10-D:I2583','ICD10-D:I2584','ICD10-D:I672','ICD10-D:I700','ICD10-D:I701','ICD10-D:I70201',
              'ICD10-D:I70202','ICD10-D:I70203','ICD10-D:I70208','ICD10-D:I70209','ICD10-D:I70211','ICD10-D:I70212','ICD10-D:I70213','ICD10-D:I70218','ICD10-D:I70219','ICD10-D:I70221','ICD10-D:I70222','ICD10-D:I70223',
              'ICD10-D:I70228','ICD10-D:I70229','ICD10-D:I70231','ICD10-D:I70232','ICD10-D:I70233','ICD10-D:I70234','ICD10-D:I70235','ICD10-D:I70238','ICD10-D:I70239','ICD10-D:I70241','ICD10-D:I70242','ICD10-D:I70243',
              'ICD10-D:I70244','ICD10-D:I70245','ICD10-D:I70248','ICD10-D:I70249','ICD10-D:I7025','ICD10-D:I70261','ICD10-D:I70262','ICD10-D:I70263','ICD10-D:I70268','ICD10-D:I70269','ICD10-D:I70291','ICD10-D:I70292',
              'ICD10-D:I70293','ICD10-D:I70298','ICD10-D:I70299','ICD10-D:I70301','ICD10-D:I70302','ICD10-D:I70303','ICD10-D:I70308','ICD10-D:I70309','ICD10-D:I70311','ICD10-D:I70312','ICD10-D:I70313','ICD10-D:I70318',
              'ICD10-D:I70319','ICD10-D:I70321','ICD10-D:I70322','ICD10-D:I70323','ICD10-D:I70328','ICD10-D:I70329','ICD10-D:I70331','ICD10-D:I70332','ICD10-D:I70333','ICD10-D:I70334','ICD10-D:I70335','ICD10-D:I70338',
              'ICD10-D:I70339','ICD10-D:I70341','ICD10-D:I70342','ICD10-D:I70343','ICD10-D:I70344','ICD10-D:I70345','ICD10-D:I70348','ICD10-D:I70349','ICD10-D:I7035','ICD10-D:I70361','ICD10-D:I70362','ICD10-D:I70363',
              'ICD10-D:I70368','ICD10-D:I70369','ICD10-D:I70391','ICD10-D:I70392','ICD10-D:I70393','ICD10-D:I70398','ICD10-D:I70399','ICD10-D:I70401','ICD10-D:I70402','ICD10-D:I70403','ICD10-D:I70408','ICD10-D:I70409',
              'ICD10-D:I70411','ICD10-D:I70412','ICD10-D:I70413','ICD10-D:I70418','ICD10-D:I70419','ICD10-D:I70421','ICD10-D:I70422','ICD10-D:I70423','ICD10-D:I70428','ICD10-D:I70429','ICD10-D:I70431','ICD10-D:I70432',
              'ICD10-D:I70433','ICD10-D:I70434','ICD10-D:I70435','ICD10-D:I70438','ICD10-D:I70439','ICD10-D:I70441','ICD10-D:I70442','ICD10-D:I70443','ICD10-D:I70444','ICD10-D:I70445','ICD10-D:I70448','ICD10-D:I70449',
              'ICD10-D:I7045','ICD10-D:I70461','ICD10-D:I70462','ICD10-D:I70463','ICD10-D:I70468','ICD10-D:I70469','ICD10-D:I70491','ICD10-D:I70492','ICD10-D:I70493','ICD10-D:I70498','ICD10-D:I70499','ICD10-D:I70501',
              'ICD10-D:I70502','ICD10-D:I70503','ICD10-D:I70508','ICD10-D:I70509','ICD10-D:I70511','ICD10-D:I70512','ICD10-D:I70513','ICD10-D:I70518','ICD10-D:I70519','ICD10-D:I70521','ICD10-D:I70522','ICD10-D:I70523',
              'ICD10-D:I70528','ICD10-D:I70529','ICD10-D:I70531','ICD10-D:I70532','ICD10-D:I70533','ICD10-D:I70534','ICD10-D:I70535','ICD10-D:I70538','ICD10-D:I70539','ICD10-D:I70541','ICD10-D:I70542','ICD10-D:I70543',
              'ICD10-D:I70544','ICD10-D:I70545','ICD10-D:I70548','ICD10-D:I70549','ICD10-D:I7055','ICD10-D:I70561','ICD10-D:I70562','ICD10-D:I70563','ICD10-D:I70568','ICD10-D:I70569','ICD10-D:I70591','ICD10-D:I70592',
              'ICD10-D:I70593','ICD10-D:I70598','ICD10-D:I70599','ICD10-D:I70601','ICD10-D:I70602','ICD10-D:I70603','ICD10-D:I70608','ICD10-D:I70609','ICD10-D:I70611','ICD10-D:I70612','ICD10-D:I70613','ICD10-D:I70618',
              'ICD10-D:I70619','ICD10-D:I70621','ICD10-D:I70622','ICD10-D:I70623','ICD10-D:I70628','ICD10-D:I70629','ICD10-D:I70631','ICD10-D:I70632','ICD10-D:I70633','ICD10-D:I70634','ICD10-D:I70635','ICD10-D:I70638',
              'ICD10-D:I70639','ICD10-D:I70641','ICD10-D:I70642','ICD10-D:I70643','ICD10-D:I70644','ICD10-D:I70645','ICD10-D:I70648','ICD10-D:I70649','ICD10-D:I7065','ICD10-D:I70661','ICD10-D:I70662','ICD10-D:I70663',
              'ICD10-D:I70668','ICD10-D:I70669','ICD10-D:I70691','ICD10-D:I70692','ICD10-D:I70693','ICD10-D:I70698','ICD10-D:I70699','ICD10-D:I70701','ICD10-D:I70702','ICD10-D:I70703','ICD10-D:I70708','ICD10-D:I70709',
              'ICD10-D:I70711','ICD10-D:I70712','ICD10-D:I70713','ICD10-D:I70718','ICD10-D:I70719','ICD10-D:I70721','ICD10-D:I70722','ICD10-D:I70723','ICD10-D:I70728','ICD10-D:I70729','ICD10-D:I70731','ICD10-D:I70732',
              'ICD10-D:I70733','ICD10-D:I70734','ICD10-D:I70735','ICD10-D:I70738','ICD10-D:I70739','ICD10-D:I70741','ICD10-D:I70742','ICD10-D:I70743','ICD10-D:I70744','ICD10-D:I70745','ICD10-D:I70748','ICD10-D:I70749',
              'ICD10-D:I7075','ICD10-D:I70761','ICD10-D:I70762','ICD10-D:I70763','ICD10-D:I70768','ICD10-D:I70769','ICD10-D:I70791','ICD10-D:I70792','ICD10-D:I70793','ICD10-D:I70798','ICD10-D:I70799','ICD10-D:I708',
              'ICD10-D:I7090','ICD10-D:I7091','ICD10-D:I440','ICD10-D:I441','ICD10-D:I442','ICD10-D:I4430','ICD10-D:I4439','ICD10-D:I447','ICD10-D:I450','ICD10-D:I4510','ICD10-D:I4519','ICD10-D:I455','ICD10-D:R001',
              'ICD10-D:O0881','ICD10-D:O29111','ICD10-D:O29112','ICD10-D:O29113','ICD10-D:O29119','ICD10-D:O29121','ICD10-D:O29122','ICD10-D:O29123','ICD10-D:O29129','ICD10-D:O29191','ICD10-D:O29192','ICD10-D:O29193',
              'ICD10-D:O29199','ICD10-D:O742','ICD10-D:O891','ICD10-D:P2981','ICD10-D:Q218','ICD10-D:Q218','ICD10-D:Q219','ICD10-D:Q219','ICD10-D:R010','ICD10-D:R011','ICD10-D:R012','ICD10-D:T826XXA','ICD10-D:T826XXD',
              'ICD10-D:T826XXS','ICD10-D:T827XXA','ICD10-D:T827XXD','ICD10-D:T827XXS','ICD10-D:T82817A','ICD10-D:T82817D','ICD10-D:T82817S','ICD10-D:T82818A','ICD10-D:T82818D','ICD10-D:T82818S','ICD10-D:T82837A','ICD10-D:T82837D',
              'ICD10-D:T82837S','ICD10-D:T82838A','ICD10-D:T82838D','ICD10-D:T82838S','ICD10-D:T82855A','ICD10-D:T82855D','ICD10-D:T82855S','ICD10-D:T82856A','ICD10-D:T82856D','ICD10-D:T82856S','ICD10-D:T82857A','ICD10-D:T82857D',
              'ICD10-D:T82857S','ICD10-D:T82858A','ICD10-D:T82858D','ICD10-D:T82858S','ICD10-D:T82867A','ICD10-D:T82867D','ICD10-D:T82867S','ICD10-D:T82868A','ICD10-D:T82868D','ICD10-D:T82868S','ICD10-D:T82897A','ICD10-D:T82897D',
              'ICD10-D:T82897S','ICD10-D:T82898A','ICD10-D:T82898D','ICD10-D:T82898S','ICD10-D:T86290','ICD10-D:Y840','ICD10-D:Z050','ICD10-D:Z3683','ICD10-D:Z4509','ICD10-D:Z8674','ICD10-D:A5200','ICD10-D:A5201','ICD10-D:A5202',
              'ICD10-D:A5203','ICD10-D:A5204','ICD10-D:A5205','ICD10-D:A5206','ICD10-D:A5209','ICD10-D:A3681','ICD10-D:B334','ICD10-D:I420','ICD10-D:I421','ICD10-D:I422','ICD10-D:I423','ICD10-D:I424','ICD10-D:I425','ICD10-D:I426',
              'ICD10-D:I427','ICD10-D:I428','ICD10-D:I429','ICD10-D:I43','ICD10-D:I495','ICD10-D:I517','ICD10-D:O903','ICD10-D:P2989','ICD10-D:P299','ICD10-D:Q87418','ICD10-D:R570','ICD10-D:R9430','ICD10-D:R9431','ICD10-D:R9439',
              'ICD10-D:T8111XA','ICD10-D:T8111XD','ICD10-D:T8111XS','ICD10-D:Y710','ICD10-D:Y711','ICD10-D:Y712','ICD10-D:Y713','ICD10-D:Y718','ICD10-D:Z136','ICD10-D:A5054','ICD10-D:A5055','ICD10-D:A5056','ICD10-D:I5020','ICD10-D:I5021',
              'ICD10-D:I5022','ICD10-D:I5023','ICD10-D:I5030','ICD10-D:I5031','ICD10-D:I5032','ICD10-D:I5033','ICD10-D:I5040','ICD10-D:I5041','ICD10-D:I5042','ICD10-D:I5043','ICD10-D:I491','ICD10-D:I492','ICD10-D:I493','ICD10-D:I4940',
              'ICD10-D:I4949','ICD10-D:I2542','ICD10-D:I670','ICD10-D:I7100','ICD10-D:I7101','ICD10-D:I7102','ICD10-D:I7103','ICD10-D:I7770','ICD10-D:I7771','ICD10-D:I7772','ICD10-D:I7773','ICD10-D:I7774','ICD10-D:I7775','ICD10-D:I7776',
              'ICD10-D:I7777','ICD10-D:I7779','ICD10-D:I480','ICD10-D:I481','ICD10-D:I482','ICD10-D:I4891','ICD10-D:I4901','ICD10-D:I483','ICD10-D:I484','ICD10-D:I484','ICD10-D:I4892','ICD10-D:I4892','ICD10-D:I4902','ICD10-D:I018',
              'ICD10-D:I019','ICD10-D:I0989','ICD10-D:I099','ICD10-D:I110','ICD10-D:I119','ICD10-D:I248','ICD10-D:I249','ICD10-D:I25111','ICD10-D:I25118','ICD10-D:I25119','ICD10-D:I2589','ICD10-D:I259','ICD10-D:I271','ICD10-D:I2722',
              'ICD10-D:I2789','ICD10-D:I279','ICD10-D:I5189','ICD10-D:I519','ICD10-D:M0530','ICD10-D:M05311','ICD10-D:M05312','ICD10-D:M05319','ICD10-D:M05321','ICD10-D:M05322','ICD10-D:M05329','ICD10-D:M05331','ICD10-D:M05332',
              'ICD10-D:M05339','ICD10-D:M05341','ICD10-D:M05342','ICD10-D:M05349','ICD10-D:M05351','ICD10-D:M05352','ICD10-D:M05359','ICD10-D:M05361','ICD10-D:M05362','ICD10-D:M05369','ICD10-D:M05371','ICD10-D:M05372','ICD10-D:M05379',
              'ICD10-D:M0539','ICD10-D:O10111','ICD10-D:O10112','ICD10-D:O10113','ICD10-D:O10119','ICD10-D:O1012','ICD10-D:T8620','ICD10-D:T8621','ICD10-D:T8622','ICD10-D:T8623','ICD10-D:T86298','ICD10-D:T8630','ICD10-D:T8631',
              'ICD10-D:T8632','ICD10-D:T8633','ICD10-D:T8639','ICD10-D:Z4821','ICD10-D:Z48280','ICD10-D:Z941','ICD10-D:Z943','ICD10-D:I2101','ICD10-D:I2102','ICD10-D:I2109','ICD10-D:I2111','ICD10-D:I2119','ICD10-D:I2121','ICD10-D:I2129',
              'ICD10-D:I213','ICD10-D:I214','ICD10-D:I219','ICD10-D:I21A1','ICD10-D:I21A9','ICD10-D:I220','ICD10-D:I221','ICD10-D:I222','ICD10-D:I228','ICD10-D:I229','ICD10-D:I230','ICD10-D:I231','ICD10-D:I232','ICD10-D:I233',
              'ICD10-D:I234','ICD10-D:I235','ICD10-D:I236','ICD10-D:I238','ICD10-D:I240','ICD10-D:I252','ICD10-D:I255','ICD10-D:I256','ICD10-D:Z45010','ICD10-D:Z45018','ICD10-D:Z950','ICD10-D:I471','ICD10-D:I472','ICD10-D:I479',
              'ICD10-D:I479','ICD10-D:I501','ICD10-D:B3320','ICD10-D:B3321','ICD10-D:B3322','ICD10-D:B3323','ICD10-D:B3324','ICD9-D:4414','ICD9-D:4413','ICD9-D:930','ICD9-D:4423','ICD9-D:44281','ICD9-D:4420','ICD9-D:41411','ICD9-D:41410',
              'ICD9-D:4422','ICD9-D:44289','ICD9-D:44284','ICD9-D:4171','ICD9-D:4421','ICD9-D:44283','ICD9-D:44282','ICD9-D:4429','ICD9-D:4419','ICD9-D:4415','ICD9-D:4373','ICD9-D:41419','ICD9-D:9487','ICD9-D:4412','ICD9-D:4411',
              'ICD9-D:4416','ICD9-D:4417','ICD9-D:4400','ICD9-D:44031','ICD9-D:44024','ICD9-D:44021','ICD9-D:44022','ICD9-D:44023','ICD9-D:44020','ICD9-D:44032','ICD9-D:4408','ICD9-D:4401','ICD9-D:44030','ICD9-D:4404','ICD9-D:4409',
              'ICD9-D:44029','ICD9-D:4260','ICD9-D:42610','ICD9-D:42611','ICD9-D:42612','ICD9-D:42613','ICD9-D:4262','ICD9-D:4263','ICD9-D:4264','ICD9-D:42650','ICD9-D:42651','ICD9-D:42652','ICD9-D:42653','ICD9-D:42654','ICD9-D:4266',
              'ICD9-D:74686','ICD9-D:77981','ICD9-D:42971','ICD9-D:4275','ICD9-D:9971','ICD9-D:4279','ICD9-D:4233','ICD9-D:V1741','ICD9-D:4294','ICD9-D:99601','ICD9-D:99604','ICD9-D:99600','ICD9-D:99609','ICD9-D:42789','ICD9-D:V1253',
              'ICD9-D:7852','ICD9-D:4255','ICD9-D:4258','ICD9-D:42511','ICD9-D:42511','ICD9-D:4257','ICD9-D:4252','ICD9-D:42518','ICD9-D:4254','ICD9-D:67453','ICD9-D:67452','ICD9-D:67451','ICD9-D:67454','ICD9-D:67450','ICD9-D:4259',
              'ICD9-D:4292','ICD9-D:3062','ICD9-D:64853','ICD9-D:64852','ICD9-D:64851','ICD9-D:64854','ICD9-D:64850','ICD9-D:64863','ICD9-D:64862','ICD9-D:64861','ICD9-D:64864','ICD9-D:64860','ICD9-D:V151','ICD9-D:74721','ICD9-D:74720',
              'ICD9-D:74722','ICD9-D:74686','ICD9-D:7464','ICD9-D:7466','ICD9-D:7465','ICD9-D:7463','ICD9-D:7462','ICD9-D:7467','ICD9-D:74729','ICD9-D:7461','ICD9-D:4280','ICD9-D:42841','ICD9-D:42831','ICD9-D:42843','ICD9-D:42833',
              'ICD9-D:42823','ICD9-D:42821','ICD9-D:42842','ICD9-D:42832','ICD9-D:42822','ICD9-D:4142','ICD9-D:42840','ICD9-D:74685','ICD9-D:41401','ICD9-D:77083','ICD9-D:42830','ICD9-D:4289','ICD9-D:40413','ICD9-D:40411','ICD9-D:40410',
              'ICD9-D:40412','ICD9-D:40401','ICD9-D:40403','ICD9-D:40402','ICD9-D:40493','ICD9-D:40491','ICD9-D:40490','ICD9-D:40492','ICD9-D:4281','ICD9-D:V4322','ICD9-D:V4321','ICD9-D:4266','ICD9-D:42820','ICD9-D:40291','ICD9-D:44102',
              'ICD9-D:44101','ICD9-D:44103','ICD9-D:44100','ICD9-D:41412','ICD9-D:4210','ICD9-D:4211','ICD9-D:4219','ICD9-D:42731','ICD9-D:42741','ICD9-D:42732','ICD9-D:42742','ICD9-D:3919','ICD9-D:40211','ICD9-D:40210','ICD9-D:4149',
              'ICD9-D:4169','ICD9-D:V173','ICD9-D:4299','ICD9-D:42982','ICD9-D:4161','ICD9-D:40201','ICD9-D:40200','ICD9-D:41189','ICD9-D:3918','ICD9-D:4168','ICD9-D:9885','ICD9-D:42989','ICD9-D:4148','ICD9-D:3920','ICD9-D:V810',
              'ICD9-D:40291','ICD9-D:40290','ICD9-D:99683','ICD9-D:V421','ICD9-D:41080','ICD9-D:41081','ICD9-D:41082','ICD9-D:41090','ICD9-D:41091','ICD9-D:41092','ICD9-D:4130','ICD9-D:412','ICD9-D:41519','ICD9-D:4110','ICD9-D:4371',
              'ICD9-D:3940','ICD9-D:3942','ICD9-D:3941','ICD9-D:3969','ICD9-D:4240','ICD9-D:3963','ICD9-D:3962','ICD9-D:3961','ICD9-D:3960','ICD9-D:3968','ICD9-D:3949','ICD9-D:9321','ICD9-D:42979','ICD9-D:4250','ICD9-D:4291','ICD9-D:V4501',
              'ICD9-D:V5331','ICD9-D:V4501','ICD9-D:99601','ICD9-D:V5331','ICD9-D:3959','ICD9-D:39899','ICD9-D:3951','ICD9-D:3950','ICD9-D:3952','ICD9-D:3979','ICD9-D:3971','ICD9-D:39890','ICD9-D:39891','ICD9-D:4270','ICD9-D:4272',
              'ICD9-D:4271','ICD9-D:7850','ICD9-D:3970','ICD9-D:7454']

stroke_icd = ['ICD10-D:I6300','ICD10-D:I63011','ICD10-D:I63012','ICD10-D:I63013','ICD10-D:I63019','ICD10-D:I6302','ICD10-D:I63031','ICD10-D:I63032','ICD10-D:I63033','ICD10-D:I63039','ICD10-D:I6309','ICD10-D:I6310','ICD10-D:I63111','ICD10-D:I63112','ICD10-D:I63113','ICD10-D:I63119','ICD10-D:I6312','ICD10-D:I63131','ICD10-D:I63132','ICD10-D:I63133','ICD10-D:I63139','ICD10-D:I6319','ICD10-D:I6320','ICD10-D:I63211','ICD10-D:I63212','ICD10-D:I63213','ICD10-D:I63219','ICD10-D:I6322','ICD10-D:I63231','ICD10-D:I63232','ICD10-D:I63233','ICD10-D:I63239','ICD10-D:I6329','ICD10-D:I6330','ICD10-D:I63311','ICD10-D:I63312','ICD10-D:I63313','ICD10-D:I63319','ICD10-D:I63321','ICD10-D:I63322','ICD10-D:I63323','ICD10-D:I63329','ICD10-D:I63331','ICD10-D:I63332','ICD10-D:I63333','ICD10-D:I63339','ICD10-D:I63341','ICD10-D:I63342','ICD10-D:I63343','ICD10-D:I63349','ICD10-D:I6339','ICD10-D:I6340','ICD10-D:I63411','ICD10-D:I63412','ICD10-D:I63413','ICD10-D:I63419','ICD10-D:I63421','ICD10-D:I63422','ICD10-D:I63423','ICD10-D:I63429','ICD10-D:I63431','ICD10-D:I63432','ICD10-D:I63433','ICD10-D:I63439','ICD10-D:I63441','ICD10-D:I63442','ICD10-D:I63443','ICD10-D:I63449','ICD10-D:I6349','ICD10-D:I6350','ICD10-D:I63511','ICD10-D:I63512','ICD10-D:I63513','ICD10-D:I63519','ICD10-D:I63521','ICD10-D:I63522','ICD10-D:I63523','ICD10-D:I63529','ICD10-D:I63531','ICD10-D:I63532','ICD10-D:I63533','ICD10-D:I63539','ICD10-D:I63541','ICD10-D:I63542','ICD10-D:I63543','ICD10-D:I63549','ICD10-D:I6359','ICD10-D:I636','ICD10-D:I6381','ICD10-D:I6389','ICD10-D:I639','ICD10-D:G458','ICD10-D:G459','ICD10-D:I6782','ICD10-D:Z8673','ICD10-D:G463','ICD10-D:G464','ICD10-D:D473','ICD10-D:Z86718','ICD9-D:43400','ICD9-D:43491','ICD9-D:43411','ICD9-D:43401','ICD9-D:99702','ICD9-D:43301','ICD9-D:43311','ICD9-D:43331','ICD9-D:43381','ICD9-D:43391','ICD9-D:43321','ICD9-D:34663','ICD9-D:34661','ICD9-D:34662','ICD9-D:34660','ICD9-D:41070','ICD9-D:41071','ICD9-D:41072','ICD9-D:43410','ICD9-D:436','ICD9-D:4350','ICD9-D:4373','ICD9-D:4374','ICD9-D:4370','ICD9-D:4372','ICD9-D:4375','ICD9-D:4376','ICD9-D:4371','ICD9-D:4378','ICD9-D:4358','ICD9-D:4352','ICD9-D:4377','ICD9-D:4379','ICD9-D:4359','ICD9-D:4351','ICD9-D:4353','ICD9-D:76870','ICD9-D:76871','ICD9-D:76872','ICD9-D:76873','ICD9-D:V171','ICD9-D:V1254']
depress_icd = ['ICD10-D:F320','ICD10-D:F321','ICD10-D:F322','ICD10-D:F323','ICD10-D:F324','ICD10-D:F325','ICD10-D:F3281','ICD10-D:F3289','ICD10-D:F329','ICD10-D:F330','ICD10-D:F331','ICD10-D:F332','ICD10-D:F333','ICD10-D:F3340','ICD10-D:F3341','ICD10-D:F3342','ICD10-D:F338','ICD10-D:F339','ICD10-D:F530','ICD10-D:F341','ICD9-D:29013','ICD9-D:29021','ICD9-D:29620','ICD9-D:29621','ICD9-D:29622','ICD9-D:29623','ICD9-D:29624','ICD9-D:29625','ICD9-D:29626','ICD9-D:29630','ICD9-D:29631','ICD9-D:29632','ICD9-D:29633','ICD9-D:29634','ICD9-D:29635','ICD9-D:29636','ICD9-D:29682','ICD9-D:2980','ICD9-D:30112','ICD9-D:311','ICD9-D:3004']
anxiety_icd = ['ICD10-D:F4322','ICD10-D:F4323','ICD10-D:F4000','ICD10-D:F4001','ICD10-D:F4002','ICD10-D:F064','ICD10-D:F10180','ICD10-D:F10280','ICD10-D:F10980','ICD10-D:F12180','ICD10-D:F12280','ICD10-D:F12980','ICD10-D:F13180','ICD10-D:F13280','ICD10-D:F13980','ICD10-D:F14180','ICD10-D:F14280','ICD10-D:F14980','ICD10-D:F15180','ICD10-D:F15280','ICD10-D:F15980','ICD10-D:F16180','ICD10-D:F16280','ICD10-D:F16980','ICD10-D:F18180','ICD10-D:F18280','ICD10-D:F18980','ICD10-D:F19180','ICD10-D:F19280','ICD10-D:F19980','ICD10-D:F408','ICD10-D:F409','ICD10-D:F411','ICD10-D:F413','ICD10-D:F418','ICD10-D:F419','ICD10-D:F930','ICD10-D:F4520','ICD10-D:F4521','ICD10-D:F4529','ICD10-D:F410','ICD10-D:F4010','ICD10-D:F4011','ICD10-D:F40298','ICD10-D:F940','ICD9-D:30924','ICD9-D:30928','ICD9-D:30021','ICD9-D:30022','ICD9-D:29384','ICD9-D:30000','ICD9-D:30002','ICD9-D:30009','ICD9-D:30921','ICD9-D:3007','ICD9-D:30001','ICD9-D:30029','ICD9-D:30023','ICD9-D:31323']
concusn_icd = ['ICD10-D:F0781','ICD10-D:S060X0A','ICD10-D:S060X0D','ICD10-D:S060X0S','ICD10-D:S060X1A','ICD10-D:S060X1D','ICD10-D:S060X1S','ICD10-D:S060X9A','ICD10-D:S060X9D','ICD10-D:S060X9S','ICD10-D:S140XXA','ICD10-D:S140XXD','ICD10-D:S140XXS','ICD10-D:S240XXA','ICD10-D:S240XXD','ICD10-D:F0781','ICD10-D:S3401XA','ICD10-D:S3401XD','ICD10-D:S3401XS','ICD10-D:S3402XA','ICD10-D:S3402XD','ICD10-D:S3402XS','ICD10-D:S062X0A','ICD10-D:S062X0D','ICD10-D:S062X0S','ICD10-D:S062X1A','ICD10-D:S062X1D','ICD10-D:S062X1S','ICD10-D:S062X2A','ICD10-D:S062X2D','ICD10-D:S062X2S','ICD10-D:S062X3A','ICD10-D:S062X3D','ICD10-D:S062X3S','ICD10-D:S062X4A','ICD10-D:S062X4D','ICD10-D:S062X4S','ICD10-D:S062X5A','ICD10-D:S062X5D','ICD10-D:S062X5S','ICD10-D:S062X6A','ICD10-D:S062X6D','ICD10-D:S062X6S','ICD10-D:S062X7A','ICD10-D:S062X8A','ICD10-D:S062X9A','ICD10-D:S062X9D','ICD10-D:S062X9S','ICD10-D:S06300A','ICD10-D:S06300D','ICD10-D:S06300S','ICD10-D:S06301A','ICD10-D:S06301D','ICD10-D:S06301S','ICD10-D:S06302A','ICD10-D:S06302D','ICD10-D:S06302S','ICD10-D:S06303A','ICD10-D:S06303D','ICD10-D:S06303S','ICD10-D:S06304A','ICD10-D:S06304D','ICD10-D:S06304S','ICD10-D:S06305A','ICD10-D:S06305D','ICD10-D:S06305S','ICD10-D:S06306A','ICD10-D:S06306D','ICD10-D:S06306S','ICD10-D:S06307A','ICD10-D:S06308A','ICD10-D:S06309A','ICD10-D:S06309D','ICD10-D:S06309S','ICD10-D:Z87820','ICD9-D:3102','ICD9-D:8500','ICD9-D:85011','ICD9-D:85012','ICD9-D:8502','ICD9-D:8503','ICD9-D:8504','ICD9-D:8505','ICD9-D:8509','ICD9-D:85300','ICD9-D:V1552','ICD9-D:95901','ICD9-D:85400']
sleepD_icd = ['ICD10-D:A8183','ICD10-D:F5101','ICD10-D:F5102','ICD10-D:F5103','ICD10-D:F5104','ICD10-D:F5105','ICD10-D:F5109','ICD10-D:G4700','ICD10-D:G4701','ICD10-D:G4709','ICD10-D:Z73810','ICD10-D:Z73811','ICD10-D:Z73812','ICD10-D:Z73819','ICD10-D:G47411','ICD10-D:G47419','ICD10-D:G47421','ICD10-D:G47429','ICD10-D:F10182','ICD10-D:F10282','ICD10-D:F10982','ICD10-D:F11182','ICD10-D:F11282','ICD10-D:F11982','ICD10-D:F13182','ICD10-D:F13282','ICD10-D:F13288','ICD10-D:F13982','ICD10-D:F14182','ICD10-D:F14282','ICD10-D:F14982','ICD10-D:F15182','ICD10-D:F15282','ICD10-D:F15982','ICD10-D:F19282','ICD10-D:F19982','ICD10-D:F5112','ICD10-D:F513','ICD10-D:F514','ICD10-D:F515','ICD10-D:F518','ICD10-D:F519','ICD10-D:G4711','ICD10-D:G4712','ICD10-D:G4720','ICD10-D:G4721','ICD10-D:G4722','ICD10-D:G4723','ICD10-D:G4724','ICD10-D:G4725','ICD10-D:G4726','ICD10-D:G4727','ICD10-D:G4729','ICD10-D:G4730','ICD10-D:G4731','ICD10-D:G4733','ICD10-D:G4734','ICD10-D:G4736','ICD10-D:G4737','ICD10-D:G4739','ICD10-D:G4752','ICD10-D:G4753','ICD10-D:G4762','ICD10-D:G4763','ICD10-D:G4769','ICD10-D:G478','ICD10-D:G479','ICD10-D:P283','ICD10-D:Z72820','ICD10-D:Z72821','ICD10-D:Z73810','ICD9-D:4672','ICD9-D:32701','ICD9-D:32702','ICD9-D:78052','ICD9-D:78052','ICD9-D:32700','ICD9-D:32709','ICD9-D:34711','ICD9-D:34710','ICD9-D:34701','ICD9-D:34700','ICD9-D:29182','ICD9-D:32727','ICD9-D:32737','ICD9-D:30745','ICD9-D:32732','ICD9-D:32731','ICD9-D:32734','ICD9-D:32733','ICD9-D:32735','ICD9-D:32736','ICD9-D:32730','ICD9-D:32725','ICD9-D:78055','ICD9-D:29285','ICD9-D:78056','ICD9-D:32722','ICD9-D:78053','ICD9-D:78054','ICD9-D:32711','ICD9-D:32712','ICD9-D:32724','ICD9-D:78051','ICD9-D:78052','ICD9-D:V694','ICD9-D:30740','ICD9-D:32723','ICD9-D:32720','ICD9-D:32739','ICD9-D:30747','ICD9-D:32729','ICD9-D:3278','ICD9-D:32759','ICD9-D:78059','ICD9-D:30749','ICD9-D:30742','ICD9-D:30744','ICD9-D:32721','ICD9-D:32743','ICD9-D:32742','ICD9-D:30748','ICD9-D:30746','ICD9-D:32726','ICD9-D:78058','ICD9-D:30741','ICD9-D:30743','ICD9-D:78057','ICD9-D:32740']
prdnts_icd = ['ICD10-D:K055','ICD10-D:K056','ICD10-D:K08121','ICD10-D:K08122','ICD10-D:K08123','ICD10-D:K08124','ICD10-D:K08129','ICD10-D:K08421','ICD10-D:K08422','ICD10-D:K08423','ICD10-D:K08424','ICD10-D:K08429','ICD10-D:K044','ICD10-D:K045','ICD10-D:K0520','ICD10-D:K05211','ICD10-D:K05212','ICD10-D:K05213','ICD10-D:K05219','ICD10-D:K05221','ICD10-D:K05222','ICD10-D:K05223','ICD10-D:K05229','ICD10-D:K0530','ICD10-D:K05311','ICD10-D:K05312','ICD10-D:K05313','ICD10-D:K05319','ICD10-D:K05321','ICD10-D:K05322','ICD10-D:K05323','ICD10-D:K05329','ICD10-D:K054','ICD9-D:5238','ICD9-D:5239','ICD9-D:5224','ICD9-D:5226','ICD9-D:52330','ICD9-D:52331','ICD9-D:52332','ICD9-D:52333','ICD9-D:52340','ICD9-D:52341','ICD9-D:52342','ICD9-D:5235']
smoke_icd = ['ICD10-D:F17200','ICD10-D:F17201','ICD10-D:F17203','ICD10-D:F17208','ICD10-D:F17209','ICD10-D:F17210','ICD10-D:F17211','ICD10-D:F17213','ICD10-D:F17218','ICD10-D:F17219','ICD10-D:F17220','ICD10-D:F17221','ICD10-D:F17223','ICD10-D:F17228','ICD10-D:F17229','ICD10-D:F17290','ICD10-D:F17291','ICD10-D:F17293','ICD10-D:F17298','ICD10-D:F17299','ICD10-D:P9681','ICD10-D:Z5731','ICD10-D:Z7722','ICD10-D:O99330','ICD10-D:O99331','ICD10-D:O99332','ICD10-D:O99333','ICD10-D:O99334','ICD10-D:O99335','ICD10-D:Z5301','ICD10-D:Z716','ICD10-D:Z720','ICD9-D:E8694','ICD9-D:3051','ICD9-D:64900','ICD9-D:64901','ICD9-D:64902','ICD9-D:64903','ICD9-D:64904','ICD9-D:V1582']
alchlA_icd = ['ICD10-D:F1010','ICD10-D:F1011','ICD10-D:F10120','ICD10-D:F10121','ICD10-D:F10129','ICD10-D:F1014','ICD10-D:F10150','ICD10-D:F10151','ICD10-D:F10159','ICD10-D:F10180','ICD10-D:F10181','ICD10-D:F10182','ICD10-D:F10188','ICD10-D:F1019','ICD10-D:F1020','ICD10-D:F1021','ICD10-D:F10220','ICD10-D:F10221','ICD10-D:F10229','ICD10-D:F10230','ICD10-D:F10231','ICD10-D:F10232','ICD10-D:F10239','ICD10-D:F1024','ICD10-D:F10250','ICD10-D:F10251','ICD10-D:F10259','ICD10-D:F1026','ICD10-D:F1027','ICD10-D:F10280','ICD10-D:F10281','ICD10-D:F10282','ICD10-D:F10288','ICD10-D:F1029','ICD10-D:F10920','ICD10-D:F10921','ICD10-D:F10929','ICD10-D:F1094','ICD10-D:F10950','ICD10-D:F10951','ICD10-D:F10959','ICD10-D:F1096','ICD10-D:F1097','ICD10-D:F10980','ICD10-D:F10981','ICD10-D:F10982','ICD10-D:F10988','ICD10-D:F1099','ICD10-D:G312','ICD10-D:G621','ICD10-D:G721','ICD10-D:I426','ICD10-D:K2920','ICD10-D:K2921','ICD10-D:K7010','ICD10-D:K7011','ICD10-D:K702','ICD10-D:K7030','ICD10-D:K7031','ICD10-D:K7040','ICD10-D:K7041','ICD10-D:K709','ICD10-D:K8520','ICD10-D:K8521','ICD10-D:K8522','ICD10-D:K860','ICD10-D:O99310','ICD10-D:O99311','ICD10-D:O99312','ICD10-D:O99313','ICD10-D:O99314','ICD10-D:O99315','ICD9-D:2910','ICD9-D:2911','ICD9-D:2912','ICD9-D:2913','ICD9-D:2914','ICD9-D:2915','ICD9-D:29181','ICD9-D:29182','ICD9-D:29189','ICD9-D:2919','ICD9-D:30300','ICD9-D:30301','ICD9-D:30302','ICD9-D:30303','ICD9-D:30390','ICD9-D:30391','ICD9-D:30392','ICD9-D:30393','ICD9-D:30500','ICD9-D:30501','ICD9-D:30502','ICD9-D:30503','ICD9-D:3575','ICD9-D:4255','ICD9-D:5710','ICD9-D:5711','ICD9-D:5712','ICD9-D:5713','ICD9-D:7903','ICD9-D:V113']

obesity = [i.split(':')[1] for i in obesity_icd]
diabetes = [i.split(':')[1] for i in diabetes_icd]
hld = [i.split(':')[1] for i in hld_icd]
htn = [i.split(':')[1] for i in htn_icd]
heart = [i.split(':')[1] for i in heartD_icd]
stroke = [i.split(':')[1] for i in stroke_icd]
depress = [i.split(':')[1] for i in depress_icd]
anxiety = [i.split(':')[1] for i in anxiety_icd]
concusn = [i.split(':')[1] for i in concusn_icd]
sleepD = [i.split(':')[1] for i in sleepD_icd]
prdnts = [i.split(':')[1] for i in prdnts_icd]
smoke = [i.split(':')[1] for i in smoke_icd]
alchlA= [i.split(':')[1] for i in alchlA_icd]
def get_m2(row):
    all_list = [i.replace('.', '') for i in row.condition_source_value]
    if len(set(all_list).intersection(set(obesity))) != 0:
        row['obesity'] = 1
    else:
        row['obesity'] = 0
    if len(set(all_list).intersection(set(diabetes))) != 0:
        row['diabetes'] = 1
    else:
        row['diabetes'] = 0

    if len(set(all_list).intersection(set(hld))) != 0:
        row['hld'] = 1
    else:
        row['hld'] = 0

    if len(set(all_list).intersection(set(htn))) != 0:
        row['htn'] = 1
    else:
        row['htn'] = 0

    if len(set(all_list).intersection(set(heart))) != 0:
        row['heart'] = 1
    else:
        row['heart'] = 0

    if len(set(all_list).intersection(set(stroke))) != 0:
        row['stroke'] = 1
    else:
        row['stroke'] = 0

    if len(set(all_list).intersection(set(depress))) != 0:
        row['depress'] = 1
    else:
        row['depress'] = 0

    if len(set(all_list).intersection(set(anxiety))) != 0:
        row['anxiety'] = 1
    else:
        row['anxiety'] = 0

    if len(set(all_list).intersection(set(concusn))) != 0:
        row['concussion'] = 1
    else:
        row['concussion'] = 0

    if len(set(all_list).intersection(set(sleepD))) != 0:
        row['sleep_disorder'] = 1
    else:
        row['sleep_disorder'] = 0

    if len(set(all_list).intersection(set(prdnts))) != 0:
        row['periodontitis'] = 1
    else:
        row['periodontitis'] = 0

    if len(set(all_list).intersection(set(smoke))) != 0:
        row['smoke'] = 1
    else:
        row['smoke'] = 0

    if len(set(all_list).intersection(set(alchlA))) != 0:
        row['alcohol_abuse'] = 1
    else:
        row['alcohol_abuse'] = 0
    return row

# 1. get location

In [4]:
person = pd.read_parquet('Deidentified OMOP/person.parquet')
print(f'all person {person.person_id.nunique()}')
# person1 = person[~person.care_site_id.isna()]
# person1 = person1[~person1.provider_id.isna()]
person1 = person[~person.location_id.isna()]
gnv = ["32601", "32602", "32603", "32604", "32605", "32606", "32607", "32608", "32609", "32610", "32611", "32612", "32614", "32627", "32635", "32641", "32653", "32667"]
jax = [
    "32081", "32099", "32201", "32202", "32203", "32204", "32205", "32206", "32207", "32208", 
    "32209", "32210", "32211", "32212", "32214", "32216", "32217", "32218", "32219", "32220", 
    "32221", "32222", "32223", "32224", "32225", "32226", "32227", "32228", "32229", "32231", 
    "32232", "32233", "32234", "32235", "32236", "32238", "32239", "32241", "32244", "32245", 
    "32246", "32247", "32250", "32254", "32255", "32256", "32257", "32258", "32259", "32260", 
    "32277"
]
location =  pd.read_parquet('Deidentified OMOP/location.parquet')
location_gnv = location[location.zip.isin(gnv)]
location_jax = location[location.zip.isin(jax)]
person_jax = person1[person1.location_id.isin(location_jax.location_id.to_list())]
person_gnv = person1[person1.location_id.isin(location_gnv.location_id.to_list())]
print(f'gnv {person_gnv.person_id.nunique()}', f'\njax {person_jax.person_id.nunique()}')

all person 46148
gnv 9302
jax 10119

In [5]:
outcome = pd.read_csv('outcome.csv')

In [6]:
outcome.outcome_sum.value_counts()

outcome_sum
mci                 33467
ad                   6168
control              4229
mci + ad             2251
not case/control       32
Name: count, dtype: int64

In [7]:
mci_ad = outcome[outcome.outcome_sum.isin(['mci + ad'])]
ad = outcome[outcome.outcome_sum.isin(['ad'])]
mci= outcome[outcome.outcome_sum.isin(['mci'])]
mci.shape, ad.shape, mci_ad.shape

((33467, 12), (6168, 12), (2251, 12))

In [8]:
# ad 6168
ad_jax = ad[ad.person_id.isin(person_jax.person_id)]
ad_gnv = ad[ad.person_id.isin(person_gnv.person_id)]
ad_jax = ad_jax.drop(columns=['first_diag_date(ad)'])
ad_gnv = ad_gnv.drop(columns=['first_diag_date(ad)'])
ad_jax.shape, ad_gnv.shape

((1550, 11), (781, 11))

In [9]:
# case 2251
mci_ad_jax = mci_ad[mci_ad.person_id.isin(person_jax.person_id)]
mci_ad_gnv = mci_ad[mci_ad.person_id.isin(person_gnv.person_id)]
mci_ad_jax = mci_ad_jax.drop(columns=['first_diag_date'])
mci_ad_gnv = mci_ad_gnv.drop(columns=['first_diag_date'])
mci_ad_jax = mci_ad_jax.rename(columns = {'first_diag_date(ad)': 'first_diag_date'})
mci_ad_gnv = mci_ad_gnv.rename(columns = {'first_diag_date(ad)': 'first_diag_date'})
mci_ad_jax.shape, mci_ad_gnv.shape

((463, 11), (576, 11))

In [10]:
mci_ad_jax['site'] = 'jax'
mci_ad_gnv['site'] = 'gnv'
ad_jax['site'] = 'jax'
ad_gnv['site'] = 'gnv'
case = pd.concat([mci_ad_jax, mci_ad_gnv, ad_jax, ad_gnv])
case.shape

(3370, 12)

In [11]:
case.head()

,person_id,condition_start_date,birth_datetime,condition_source_value,outcome_mci,outcome_ad,outcome_control,time_period,outcome_sum,index_age,first_diag_date,site
240,6986752842,2023-05-06,1952-01-25,"['F05', 'G30.9', 'G30.9', 'E78.5', 'F02.80', '...",1,1,0,0.0,mci + ad,71.0,2023-05-06,jax
926,6986998921,2022-05-10,1960-04-11,"['N18.9', 'I25.10', 'R45.851', 'E11.9', 'J45.9...",1,1,0,0.0,mci + ad,62.0,2023-02-25,jax
1049,6987021399,2022-10-05,1947-03-26,"['R60.0', 'E03.9', 'E03.9', 'R41.3', 'R41.3', ...",1,1,0,10.0,mci + ad,75.0,2023-01-19,jax
1294,6987060229,2022-11-01,1937-12-21,"['I10', 'I10', 'Zipcode', 'SMOKING STATUS', '3...",1,1,0,1.0,mci + ad,85.0,2023-12-19,jax
1441,6987083318,2023-01-09,1932-06-05,"['R55', 'R55', 'G30.9', 'F02.80', 'F02.80', 'G...",1,1,0,1.0,mci + ad,90.0,2022-11-28,jax

In [12]:
# control 33467
mci_jax = mci[mci.person_id.isin(person_jax.person_id)]
mci_gnv = mci[mci.person_id.isin(person_gnv.person_id)]
mci_jax.shape, mci_gnv.shape

((7078, 12), (7221, 12))

In [13]:
mci_jax['site'] = 'jax'
mci_gnv['site'] = 'gnv'
control = pd.concat([mci_jax, mci_gnv])
control = control.drop(columns=['first_diag_date(ad)'])
control.shape

/scratch/local/56262023/ipykernel_353087/2959490042.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mci_jax['site'] = 'jax'
/scratch/local/56262023/ipykernel_353087/2959490042.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mci_gnv['site'] = 'gnv'

(14299, 12)

In [14]:
case.shape, control.shape

((3370, 12), (14299, 12))

In [15]:
case.outcome_sum.value_counts()

outcome_sum
ad          2331
mci + ad    1039
Name: count, dtype: int64

In [16]:
case

,person_id,condition_start_date,birth_datetime,condition_source_value,outcome_mci,outcome_ad,outcome_control,time_period,outcome_sum,index_age,first_diag_date,site
240,6986752842,2023-05-06,1952-01-25,"['F05', 'G30.9', 'G30.9', 'E78.5', 'F02.80', '...",1,1,0,0.0,mci + ad,71.0,2023-05-06,jax
926,6986998921,2022-05-10,1960-04-11,"['N18.9', 'I25.10', 'R45.851', 'E11.9', 'J45.9...",1,1,0,0.0,mci + ad,62.0,2023-02-25,jax
1049,6987021399,2022-10-05,1947-03-26,"['R60.0', 'E03.9', 'E03.9', 'R41.3', 'R41.3', ...",1,1,0,10.0,mci + ad,75.0,2023-01-19,jax
1294,6987060229,2022-11-01,1937-12-21,"['I10', 'I10', 'Zipcode', 'SMOKING STATUS', '3...",1,1,0,1.0,mci + ad,85.0,2023-12-19,jax
1441,6987083318,2023-01-09,1932-06-05,"['R55', 'R55', 'G30.9', 'F02.80', 'F02.80', 'G...",1,1,0,1.0,mci + ad,90.0,2022-11-28,jax
...,...,...,...,...,...,...,...,...,...,...,...,...
45697,6994758548,2017-06-19,1930-12-19,"['G30.9', 'G30.9', 'F02.80', 'S51.001A', 'F02....",0,1,0,11.0,ad,86.0,2017-06-19,gnv
45992,6994804666,2013-11-08,1937-12-04,"['591', '592.1', '592.0', '591', '591', '331.0...",0,1,0,10.0,ad,75.0,2013-11-08,gnv
46003,6994807332,2012-04-05,1932-08-03,"['331.0', '331.0', 'Payer', 'SMOKING STATUS', ...",0,1,0,9.0,ad,79.0,2012-04-05,gnv
46101,6994821246,2013-05-11,1930-03-07,"['788.30', '788.30', '788.30', '331.0', '788.3...",0,1,0,9.0,ad,83.0,2013-05-11,gnv
46115,6994823175,2018-07-13,1943-08-20,"['E03.9', 'R05', 'J44.9', 'F02.81', 'F02.80', ...",0,1,0,6.0,ad,74.0,2018-07-13,gnv

In [35]:
case.to_csv('case_location.csv',index=False)
control.to_csv('control_location.csv',index=False)

## resmaple (if needed)

In [262]:
# case 100
# mci_ad_jax_50 = mci_ad_jax.person_id.sample(n=50, random_state=42)
# mci_ad_gnv_50 = mci_ad_gnv.person_id.sample(n=50, random_state=42)
mci_ad_jax_50 = mci_ad_jax.person_id
mci_ad_gnv_50 = mci_ad_gnv.person_id
mci_ad_person_100 = pd.concat([person_jax[person_jax.person_id.isin(mci_ad_jax_50)], person_gnv[person_gnv.person_id.isin(mci_ad_gnv_50)]])

In [263]:
case_jax_50 = pd.DataFrame(mci_ad_jax_50).reset_index(drop=True)
case_jax_50['site'] = 'jax'
case_gnv_50 = pd.DataFrame(mci_ad_gnv_50).reset_index(drop=True)
case_gnv_50['site'] = 'gnv'
case_location_100 = pd.concat([case_jax_50, case_gnv_50])
case_location_100.to_csv('case_location_100', index=False)

In [204]:
# control
mci_jax_50 = mci_jax.person_id.sample(n=500, random_state=42)
mci_gnv_50 = mci_gnv.person_id.sample(n=500, random_state=42)
mci_person_100 = pd.concat([person_jax[person_jax.person_id.isin(mci_jax_50)], person_gnv[person_gnv.person_id.isin(mci_gnv_50)]])

In [205]:
# control
control_jax_50 = pd.DataFrame(mci_jax_50).reset_index(drop=True)
control_jax_50['site'] = 'jax'
control_gnv_50 = pd.DataFrame(mci_gnv_50).reset_index(drop=True)
control_gnv_50['site'] = 'gnv'
control_location_100 = pd.concat([control_jax_50, control_gnv_50])
control_location_100.to_csv('control_location_1000', index=False)

# 2. get sub sample

In [2]:
def sample_100(df, ID, sample, name):
    df[df[ID].isin(sample)].to_csv(os.path.join(save, f'{name}.csv'), index=False)

In [3]:
case = pd.read_csv('case_location.csv')
control = pd.read_csv('control_location.csv')
case.shape, control.shape

((3370, 12), (14299, 12))

In [4]:
save = 'case_all'
os.makedirs(save, exist_ok=True)
person_100 = case
for i in ['observation.parquet',
 'person.parquet',
 'observation_period.parquet',
 'measurement.parquet',
 'procedure_occurrence.parquet',
 # 'provider.parquet',
 'death.parquet',
 'episode.parquet',
 'visit_occurrence.parquet',
 'condition_era.parquet',
 # 'location.parquet',
 'visit_detail.parquet',
 'drug_exposure.parquet',
 'condition_occurrence.parquet',
 # 'care_site.parquet'
         ]:
    if i == 'provider.parquet':
        sample = person_100.provider_id.to_list()
        ID = f'provider_id'
    elif i == 'location.parquet':
        sample = person_100.location_id.to_list()
        ID = f'location_id'
    elif i == 'care_site.parquet':
        sample = person_100.care_site_id.to_list()
        ID = f'care_site_id'
    else:
        sample = person_100.person_id.to_list()
        ID = 'person_id'
    df = pd.read_parquet(f'Deidentified OMOP/{i}')
    name = i.split('.')[0]
    sample_100(df, ID, sample, name)

In [6]:
save = 'control_all'
os.makedirs(save, exist_ok=True)
person_100 = control
for i in ['observation.parquet',
 'person.parquet',
 'observation_period.parquet',
 'measurement.parquet',
 'procedure_occurrence.parquet',
 # 'provider.parquet',
 'death.parquet',
 'episode.parquet',
 'visit_occurrence.parquet',
 'condition_era.parquet',
 # 'location.parquet',
 'visit_detail.parquet',
 'drug_exposure.parquet',
 'condition_occurrence.parquet',
 # 'care_site.parquet'
         ]:
    if i == 'provider.parquet':
        sample = person_100.provider_id.to_list()
        ID = f'provider_id'
    elif i == 'location.parquet':
        sample = person_100.location_id.to_list()
        ID = f'location_id'
    elif i == 'care_site.parquet':
        sample = person_100.care_site_id.to_list()
        ID = f'care_site_id'
    else:
        sample = person_100.person_id.to_list()
        ID = 'person_id'
    df = pd.read_parquet(f'Deidentified OMOP/{i}')
    name = i.split('.')[0]
    sample_100(df, ID, sample, name)

# 3. get notes

In [37]:
note_mapping = pd.read_parquet('Deidentified Metadata/IRB202001888_CLINICAL_NOTE.parquet')[['DEID_NOTE_ID', 'deid_patient_key','EncounterDate']]
all_note = pd.DataFrame()
for i in range(1,21):
    temp = pd.read_parquet(f'Deidentified Notes/IRB202001888_CLINICAL_NOTE_{i}.parquet')
    all_note = pd.concat([all_note, temp])
print(all_note.shape)
all_note.columns = ['DEID_NOTE_ID', 'text']
merged_note = pd.merge(all_note, note_mapping, on='DEID_NOTE_ID', how='inner')
merged_note.shape
merged_note.to_csv('merged-note.csv')

(16896462, 2)

In [7]:
# 15899
merged_note = pd.read_csv('merged-note.csv')
merged_note.shape

(158889, 5)

In [8]:
per = pd.read_csv('case_all/person.csv')
per_note = merged_note[merged_note.deid_patient_key.isin(per.person_id)]
per_note.to_csv('case_all/all_notes.csv', index=False)

In [9]:
per = pd.read_csv('control_all/person.csv')
per_note = merged_note[merged_note.deid_patient_key.isin(per.person_id)]
per_note.to_csv('control_all/all_notes.csv', index=False)

# 4. extract features

In [40]:
root = 'case_all'
person = pd.read_csv(os.path.join(root, 'person.csv'))
condition = pd.read_csv(os.path.join(root, 'condition_occurrence.csv'))[['person_id', 'condition_start_date', 'condition_source_value']]
observation = pd.read_csv(os.path.join(root, 'observation.csv'))[['person_id','observation_date', 'observation_source_value']]
observation.columns = ['person_id', 'condition_start_date', 'condition_source_value']
condition_all = pd.concat([condition, observation])
cols = ['person_id','birth_datetime','gender_source_value','race_source_value','ethnicity_source_value']
temp = pd.merge(condition_all, person[cols], on='person_id', how='left')
print(temp.shape)
df_agg = temp.groupby(['person_id','condition_start_date']).agg(
    {
        'person_id':'first', 
        'condition_start_date':'first',
        'condition_source_value': list,
        'birth_datetime':'first',
        'gender_source_value':'first',
        'race_source_value':'first',
        'ethnicity_source_value':'first'     
    }
)
print(df_agg.shape)

(4806030, 7)
(379499, 7)

In [41]:
df_agg.person_id.nunique()

3370

In [42]:
mci_list = ["G31.84", "F06.7", "F06.70", "F06.71", "F09", "R41.840", "R41.841", "R41.89", "R41.9"]
mci_list_no_dots = [code.replace('.', '') for code in mci_list]
mci_list9 = ["331.83", "294.9"]
mci_list9_no_dots = [code.replace('.', '') for code in mci_list9]
mci_list = mci_list + mci_list_no_dots + mci_list9 + mci_list9_no_dots

ad_list =  ["G30", "G30.0", "G30.1", "G30.8", "G30.9"]
ad_list_no_dots = [code.replace('.', '') for code in ad_list]
ad_list9 = ['331.0']
ad_list9_no_dots = [code.replace('.', '') for code in ad_list9]
ad_list = ad_list + ad_list_no_dots + ad_list9 + ad_list9_no_dots

not_control_list = [
    "290.0", "290.10", "290.11", "290.12", "290.13", "290.2", "290.21", "290.3", "290.4", "290.40",
    "290.41", "290.42", "290.43", "290.8", "290.9", "291.2", "292.82", "294.0", "294.1", "294.11",
    "294.2", "294.21", "294.8", "331", "331.1", "331.11", "331.19", "331.2", "331.3", "331.4",
    "331.5", "331.6", "331.7", "331.81", "331.82", "331.89", "332", "332.0", "332.1", "348.81",
    "437.0", "437.1", "437.2", "437.3", "437.4", "437.5", "437.6", "437.7", "437.8", "437.9",
    "797", "A81.0", "F00", "F01", "F01.5", "F01.50", "F01.51", "F02", "F02.80", "F02.81",
    "F03", "F03.90", "F03.91", "F04", "F05", "F05.1", "F06.0", "F06.1", "F06.8", "F10.27",
    "F10.6", "F10.97", "F13.27", "F13.97", "F18.17", "F18.27", "F18.97", "F19.17", "F19.27", "F19.97",
    "G13.8", "G20", "G21", "G21.1", "G21.11", "G21.19", "G21.2", "G21.3", "G21.4", "G21.8",
    "G21.9", "G30", "G30.0", "G30.1", "G30.8", "G30.9", "G31.0", "G31.01", "G31.09", "G31.1",
    "G31.2", "G31.8", "G31.83", "G31.85", "G31.89", "G31.9", "G45.4", "G91.0", "G91.1", "G91.2",
    "G93.7", "G93.81", "G94", "I67.1", "I67.2", "I67.3", "I67.4", "I67.5", "I67.6", "I67.7",
    "I67.81", "I67.82", "I67.89", "I67.9", "R41.81", "R54", "294.9", "331.83", "G31.84", "F06.7",
    "F06.71", "F06.70", "F09"
]
not_control_list_no_dots = [code.replace('.', '') for code in not_control_list]

not_control_list = not_control_list + not_control_list_no_dots + mci_list + ad_list
def get_outcome(row):
#     extract each row's outcome for each subject
        value = row.condition_source_value
        mci = 0
        ad = 0
        control = 0
        if len(set(value).intersection(set(mci_list))) != 0:
            mci = 1
        if len(set(value).intersection(set(ad_list))) != 0:
            ad = 1
        if len(set(value).intersection(set(not_control_list))) == 0:
            control = 1
        row['outcome_mci'] = mci
        row['outcome_ad'] = ad
        row['outcome_control'] = control
        return row
    
def return_outcome(df):
    df = df.apply(get_outcome, axis = 1)
    df.condition_start_date = pd.to_datetime(df.condition_start_date)
    df.birth_datetime = pd.to_datetime(df.birth_datetime)
    df = df.sort_values(by ='condition_start_date', ascending = True)
#     each patient time period
    df['time_period'] = np.floor((df.iloc[-1,1] - df.iloc[0,1]).days/365.25)
#     adding index age and oct age
    
#     control
    if (df.outcome_mci.sum() == 0) and (df.outcome_ad.sum() == 0) and (df.outcome_control.sum() == 0):
        df['outcome_sum'] = 'not case/control'
        df['index_age'] = np.floor((pd.to_datetime(df.iloc[0,1]) - pd.to_datetime(df.iloc[0,2])).days / 365.25)
        df['first_diag_date'] = df.iloc[0,1]
        df['first_diag_date(ad)'] = np.nan
        return df.head(1)
    elif (df.outcome_mci.sum() == 0) and (df.outcome_ad.sum() == 0) and (df.outcome_control.sum() != 0):
        df['outcome_sum'] = 'control'
        df['index_age'] = np.floor((pd.to_datetime(df.iloc[0,1]) - pd.to_datetime(df.iloc[0,2])).days / 365.25)
        df['first_diag_date'] = df.iloc[0,1]
        df['first_diag_date(ad)'] = np.nan
        df.outcome_control = 1
        return df.head(1)
#         mci
    elif (df.outcome_mci.sum() != 0) and (df.outcome_ad.sum() == 0):
        df['outcome_sum'] = 'mci'
#         first mci diagnosis index age
        df['index_age'] = np.floor((pd.to_datetime(df[df.outcome_mci == 1].head(1).condition_start_date.values[0]) - pd.to_datetime(df[df.outcome_mci == 1].head(1).birth_datetime.values[0])).days / 365.25)
        df_start = df[df.outcome_mci == 1]
        df_start['first_diag_date'] = df_start.iloc[0,1]
        df_start['first_diag_date(ad)'] = np.nan
        return df_start.head(1)
#     ad
    elif (df.outcome_mci.sum() == 0) and (df.outcome_ad.sum() != 0):
        df['outcome_sum'] = 'ad'
#         first ad diagnosis index age
        df['index_age'] = np.floor((pd.to_datetime(df[df.outcome_ad == 1].head(1).condition_start_date.values[0]) - pd.to_datetime(df[df.outcome_ad == 1].head(1).birth_datetime.values[0])).days / 365.25)
        df_start = df[df.outcome_ad == 1]
        df_start['first_diag_date'] = df_start.iloc[0,1]
        df_start['first_diag_date(ad)'] = np.nan
        return df_start.head(1)
#     ad + mci
    elif (df.outcome_mci.sum() != 0) and (df.outcome_ad.sum() != 0):
#         for the ad_mci, their condition start date is first mci date, index age is ad age
        df['outcome_sum'] = 'mci + ad'
        df['index_age'] = np.floor((pd.to_datetime(df[df.outcome_ad == 1].head(1).condition_start_date.values[0]) - pd.to_datetime(df[df.outcome_ad == 1].head(1).birth_datetime.values[0])).days / 365.25)
        df_ad_date = df[df.outcome_ad == 1].iloc[0,1]
        df_start = df[df.outcome_mci == 1]
        df_start['first_diag_date'] = df_start.iloc[0,1]
        df_start['first_diag_date(ad)'] = df_ad_date
        df_start.outcome_ad = 1
        return df_start.head(1)
    else:
        print('unknown')
        return None

In [43]:
from tqdm import tqdm 
tqdm.pandas()
result = df_agg.reset_index(drop=True).groupby('person_id').progress_apply(return_outcome)
result.reset_index(drop = True, inplace = True)

100%|██████████| 3370/3370 [07:37<00:00,  7.37it/s]

In [44]:
temp0 = result[result.outcome_sum == 'ad'].drop(columns = 'first_diag_date(ad)')
temp = result[result.outcome_sum == 'mci + ad'].drop(columns = 'first_diag_date')
temp = temp.rename(columns={'first_diag_date(ad)': 'first_diag_date'})
result = pd.concat([temp0,temp])
result.shape

(3370, 14)

In [45]:
baseline = result[['person_id', 'first_diag_date']]
baseline['1year'] = pd.to_datetime(baseline['first_diag_date']) - pd.DateOffset(months=12)
baseline['3year'] = pd.to_datetime(baseline['first_diag_date']) - pd.DateOffset(months=36)
baseline['5year'] = pd.to_datetime(baseline['first_diag_date']) - pd.DateOffset(months=60)

/scratch/local/56132859/ipykernel_284924/1890596131.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline['1year'] = pd.to_datetime(baseline['first_diag_date']) - pd.DateOffset(months=12)
/scratch/local/56132859/ipykernel_284924/1890596131.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline['3year'] = pd.to_datetime(baseline['first_diag_date']) - pd.DateOffset(months=36)
/scratch/local/56132859/ipykernel_284924/1890596131.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline['5year'] = pd.to_datetime(baseline['first_diag_date']) - pd.DateOffset(months=60)

In [28]:
baseline.to_csv('case_baseline.csv', index=False)

In [17]:
pd.read_csv('case_baseline.csv')

       person_id first_diag_date       1year       3year       5year
0     6986701922      2023-06-01  2022-06-01  2020-06-01  2018-06-01
1     6986702078      2023-06-06  2022-06-06  2020-06-06  2018-06-06
2     6986703448      2023-05-28  2022-05-28  2020-05-28  2018-05-28
3     6986708252      2023-07-19  2022-07-19  2020-07-19  2018-07-19
4     6986709305      2023-06-10  2022-06-10  2020-06-10  2018-06-10
...          ...             ...         ...         ...         ...
3365  6994801126      2023-09-20  2022-09-20  2020-09-20  2018-09-20
3366  6994802402      2014-07-09  2013-07-09  2011-07-09  2009-07-09
3367  6994810544      2020-08-11  2019-08-11  2017-08-11  2015-08-11
3368  6994816363      2017-02-20  2016-02-20  2014-02-20  2012-02-20
3369  6994824877      2015-01-23  2014-01-23  2012-01-23  2010-01-23

[3370 rows x 5 columns]

## control

In [29]:
mci_list = ["G31.84", "F06.7", "F06.70", "F06.71", "F09", "R41.840", "R41.841", "R41.89", "R41.9"]
mci_list_no_dots = [code.replace('.', '') for code in mci_list]
mci_list9 = ["331.83", "294.9"]
mci_list9_no_dots = [code.replace('.', '') for code in mci_list9]
mci_list = mci_list + mci_list_no_dots + mci_list9 + mci_list9_no_dots

ad_list =  ["G30", "G30.0", "G30.1", "G30.8", "G30.9"]
ad_list_no_dots = [code.replace('.', '') for code in ad_list]
ad_list9 = ['331.0']
ad_list9_no_dots = [code.replace('.', '') for code in ad_list9]
ad_list = ad_list + ad_list_no_dots + ad_list9 + ad_list9_no_dots

not_control_list = [
    "290.0", "290.10", "290.11", "290.12", "290.13", "290.2", "290.21", "290.3", "290.4", "290.40",
    "290.41", "290.42", "290.43", "290.8", "290.9", "291.2", "292.82", "294.0", "294.1", "294.11",
    "294.2", "294.21", "294.8", "331", "331.1", "331.11", "331.19", "331.2", "331.3", "331.4",
    "331.5", "331.6", "331.7", "331.81", "331.82", "331.89", "332", "332.0", "332.1", "348.81",
    "437.0", "437.1", "437.2", "437.3", "437.4", "437.5", "437.6", "437.7", "437.8", "437.9",
    "797", "A81.0", "F00", "F01", "F01.5", "F01.50", "F01.51", "F02", "F02.80", "F02.81",
    "F03", "F03.90", "F03.91", "F04", "F05", "F05.1", "F06.0", "F06.1", "F06.8", "F10.27",
    "F10.6", "F10.97", "F13.27", "F13.97", "F18.17", "F18.27", "F18.97", "F19.17", "F19.27", "F19.97",
    "G13.8", "G20", "G21", "G21.1", "G21.11", "G21.19", "G21.2", "G21.3", "G21.4", "G21.8",
    "G21.9", "G30", "G30.0", "G30.1", "G30.8", "G30.9", "G31.0", "G31.01", "G31.09", "G31.1",
    "G31.2", "G31.8", "G31.83", "G31.85", "G31.89", "G31.9", "G45.4", "G91.0", "G91.1", "G91.2",
    "G93.7", "G93.81", "G94", "I67.1", "I67.2", "I67.3", "I67.4", "I67.5", "I67.6", "I67.7",
    "I67.81", "I67.82", "I67.89", "I67.9", "R41.81", "R54", "294.9", "331.83", "G31.84", "F06.7",
    "F06.71", "F06.70", "F09"
]
not_control_list_no_dots = [code.replace('.', '') for code in not_control_list]

not_control_list = not_control_list + not_control_list_no_dots + mci_list + ad_list
def get_outcome(row):
#     extract each row's outcome for each subject
        value = row.condition_source_value
        mci = 0
        ad = 0
        control = 0
        if len(set(value).intersection(set(mci_list))) != 0:
            mci = 1
        if len(set(value).intersection(set(ad_list))) != 0:
            ad = 1
        if len(set(value).intersection(set(not_control_list))) == 0:
            control = 1
        row['outcome_mci'] = mci
        row['outcome_ad'] = ad
        row['outcome_control'] = control
        return row
    
def return_outcome(df):
    df = df.apply(get_outcome, axis = 1)
    df.condition_start_date = pd.to_datetime(df.condition_start_date)
    df.birth_datetime = pd.to_datetime(df.birth_datetime)
    df = df.sort_values(by ='condition_start_date', ascending = True)
#     each patient time period
    df['time_period'] = np.floor((df.iloc[-1,1] - df.iloc[0,1]).days/365.25)
#     adding index age and oct age
    
#     control
    if (df.outcome_mci.sum() == 0) and (df.outcome_ad.sum() == 0) and (df.outcome_control.sum() == 0):
        df['outcome_sum'] = 'not case/control'
        df['index_age'] = np.floor((pd.to_datetime(df.iloc[0,1]) - pd.to_datetime(df.iloc[0,2])).days / 365.25)
        df['first_diag_date'] = df.iloc[0,1]
        df['first_diag_date(ad)'] = np.nan
        return df.head(1)
    elif (df.outcome_mci.sum() == 0) and (df.outcome_ad.sum() == 0) and (df.outcome_control.sum() != 0):
        df['outcome_sum'] = 'control'
        df['index_age'] = np.floor((pd.to_datetime(df.iloc[0,1]) - pd.to_datetime(df.iloc[0,2])).days / 365.25)
        df['first_diag_date'] = df.iloc[0,1]
        df['first_diag_date(ad)'] = np.nan
        df.outcome_control = 1
        return df.head(1)
#         mci
    elif (df.outcome_mci.sum() != 0) and (df.outcome_ad.sum() == 0):
        df['outcome_sum'] = 'mci'
#         first mci diagnosis index age
        df['index_age'] = np.floor((pd.to_datetime(df[df.outcome_mci == 1].head(1).condition_start_date.values[0]) - pd.to_datetime(df[df.outcome_mci == 1].head(1).birth_datetime.values[0])).days / 365.25)
        df_start = df[df.outcome_mci == 1]
        df_start['first_diag_date'] = df_start.iloc[0,1]
        df_start['first_diag_date(ad)'] = np.nan
        return df_start.head(1)
#     ad
    elif (df.outcome_mci.sum() == 0) and (df.outcome_ad.sum() != 0):
        df['outcome_sum'] = 'ad'
#         first ad diagnosis index age
        df['index_age'] = np.floor((pd.to_datetime(df[df.outcome_ad == 1].head(1).condition_start_date.values[0]) - pd.to_datetime(df[df.outcome_ad == 1].head(1).birth_datetime.values[0])).days / 365.25)
        df_start = df[df.outcome_ad == 1]
        df_start['first_diag_date'] = df_start.iloc[0,1]
        df_start['first_diag_date(ad)'] = np.nan
        return df_start.head(1)
#     ad + mci
    elif (df.outcome_mci.sum() != 0) and (df.outcome_ad.sum() != 0):
#         for the ad_mci, their condition start date is first mci date, index age is ad age
        df['outcome_sum'] = 'mci + ad'
        df['index_age'] = np.floor((pd.to_datetime(df[df.outcome_ad == 1].head(1).condition_start_date.values[0]) - pd.to_datetime(df[df.outcome_ad == 1].head(1).birth_datetime.values[0])).days / 365.25)
        df_ad_date = df[df.outcome_ad == 1].iloc[0,1]
        df_start = df[df.outcome_mci == 1]
        df_start['first_diag_date'] = df_start.iloc[0,1]
        df_start['first_diag_date(ad)'] = df_ad_date
        df_start.outcome_ad = 1
        return df_start.head(1)
    else:
        print('unknown')
        return None

In [30]:
root = 'control_all'
person = pd.read_csv(os.path.join(root, 'person.csv'))
condition = pd.read_csv(os.path.join(root, 'condition_occurrence.csv'))[['person_id', 'condition_start_date', 'condition_source_value']]
observation = pd.read_csv(os.path.join(root, 'observation.csv'))[['person_id','observation_date', 'observation_source_value']]
observation.columns = ['person_id', 'condition_start_date', 'condition_source_value']
condition_all = pd.concat([condition, observation])
cols = ['person_id','birth_datetime','gender_source_value','race_source_value','ethnicity_source_value']
temp = pd.merge(condition_all, person[cols], on='person_id', how='left')
print(temp.shape)
df_agg = temp.groupby(['person_id','condition_start_date']).agg(
    {
        'person_id':'first', 
        'condition_start_date':'first',
        'condition_source_value': list,
        'birth_datetime':'first',
        'gender_source_value':'first',
        'race_source_value':'first',
        'ethnicity_source_value':'first'     
    }
)
print(df_agg.shape)
from tqdm import tqdm 
tqdm.pandas()
result = df_agg.reset_index(drop=True).groupby('person_id').progress_apply(return_outcome)
result.reset_index(drop = True, inplace = True)
baseline = result[['person_id', 'first_diag_date']]
baseline['1year'] = pd.to_datetime(baseline['first_diag_date']) - pd.DateOffset(months=12)
baseline['3year'] = pd.to_datetime(baseline['first_diag_date']) - pd.DateOffset(months=36)
baseline['5year'] = pd.to_datetime(baseline['first_diag_date']) - pd.DateOffset(months=60)
baseline.to_csv('control_baseline.csv', index=False)

(24728084, 7)
(1999064, 7)

100%|██████████| 14299/14299 [40:30<00:00,  5.88it/s]
/scratch/local/56132859/ipykernel_284924/3300401036.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline['1year'] = pd.to_datetime(baseline['first_diag_date']) - pd.DateOffset(months=12)
/scratch/local/56132859/ipykernel_284924/3300401036.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline['3year'] = pd.to_datetime(baseline['first_diag_date']) - pd.DateOffset(months=36)
/scratch/local/56132859/ipykernel_284924/3300401036.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline['5year'] = pd.to_datetime(baseline['first_diag_date']) - pd.DateOffset(months=60)

In [18]:
pd.read_csv('control_baseline.csv')

        person_id first_diag_date       1year       3year       5year
0      6986700915      2023-09-21  2022-09-21  2020-09-21  2018-09-21
1      6986702084      2023-12-11  2022-12-11  2020-12-11  2018-12-11
2      6986704530      2023-10-03  2022-10-03  2020-10-03  2018-10-03
3      6986704851      2023-05-31  2022-05-31  2020-05-31  2018-05-31
4      6986704969      2023-07-05  2022-07-05  2020-07-05  2018-07-05
...           ...             ...         ...         ...         ...
14294  6994825931      2017-10-18  2016-10-18  2014-10-18  2012-10-18
14295  6994826289      2013-12-19  2012-12-19  2010-12-19  2008-12-19
14296  6994826780      2021-10-27  2020-10-27  2018-10-27  2016-10-27
14297  6994826786      2016-01-08  2015-01-08  2013-01-08  2011-01-08
14298  6994826804      2013-10-09  2012-10-09  2010-10-09  2008-10-09

[14299 rows x 5 columns]

# 5. get demog

In [46]:
demog = pd.merge(result[['person_id', 'index_age', 'birth_datetime', 'gender_source_value', 'race_source_value', 'ethnicity_source_value']], baseline, on='person_id', how='left')

In [47]:
def get_race(row):
    if row.ethnicity_source_value == 'HISPANIC':
        row['race_ethnicity'] = 'HISPANIC'
    else:
        if row.race_source_value == 'WHITE':
            row['race_ethnicity'] = 'NHW'
        elif row.race_source_value == 'BLACK':
            row['race_ethnicity'] = 'NHB'
        elif row.race_source_value == 'UNKNOWN':
            row['race_ethnicity'] = 'UNKNOWN'
        else:
            row['race_ethnicity'] = 'OTHER'
    return row

In [48]:
t = demog.apply(get_race, axis=1)
t.to_csv('case_demog.csv', index=False)

In [19]:
pd.read_csv('case_demog.csv')

,person_id,index_age,birth_datetime,gender_source_value,race_source_value,ethnicity_source_value,first_diag_date,1year,3year,5year,race_ethnicity
0,6986701922,90.0,1932-06-03,MALE,WHITE,NOT HISPANIC,2023-06-01,2022-06-01,2020-06-01,2018-06-01,NHW
1,6986702078,86.0,1937-01-08,FEMALE,WHITE,NOT HISPANIC,2023-06-06,2022-06-06,2020-06-06,2018-06-06,NHW
2,6986703448,87.0,1936-04-16,FEMALE,OTHER,HISPANIC,2023-05-28,2022-05-28,2020-05-28,2018-05-28,HISPANIC
3,6986708252,95.0,1928-06-20,FEMALE,WHITE,HISPANIC,2023-07-19,2022-07-19,2020-07-19,2018-07-19,HISPANIC
4,6986709305,78.0,1945-03-08,MALE,OTHER,HISPANIC,2023-06-10,2022-06-10,2020-06-10,2018-06-10,HISPANIC
...,...,...,...,...,...,...,...,...,...,...,...
3365,6994801126,82.0,1941-03-15,FEMALE,WHITE,NOT HISPANIC,2023-09-20,2022-09-20,2020-09-20,2018-09-20,NHW
3366,6994802402,67.0,1946-11-10,FEMALE,BLACK,NOT HISPANIC,2014-07-09,2013-07-09,2011-07-09,2009-07-09,NHB
3367,6994810544,93.0,1926-09-06,FEMALE,WHITE,NOT HISPANIC,2020-08-11,2019-08-11,2017-08-11,2015-08-11,NHW
3368,6994816363,86.0,1930-10-11,FEMALE,BLACK,NOT HISPANIC,2017-02-20,2016-02-20,2014-02-20,2012-02-20,NHB
3369,6994824877,83.0,1931-02-16,MALE,BLACK,NOT HISPANIC,2015-01-23,2014-01-23,2012-01-23,2010-01-23,NHB

## control

In [31]:
baseline.shape

(14299, 5)

In [34]:
demog = pd.merge(result[['person_id', 'index_age', 'birth_datetime', 'gender_source_value', 'race_source_value', 'ethnicity_source_value']], baseline, on='person_id', how='left')
t = demog.apply(get_race, axis=1)
t.to_csv('control_demog.csv', index=False)

In [62]:
pd.read_csv('control_baseline.csv')

        person_id first_diag_date       1year       3year       5year
0      6986700915      2023-09-21  2022-09-21  2020-09-21  2018-09-21
1      6986702084      2023-12-11  2022-12-11  2020-12-11  2018-12-11
2      6986704530      2023-10-03  2022-10-03  2020-10-03  2018-10-03
3      6986704851      2023-05-31  2022-05-31  2020-05-31  2018-05-31
4      6986704969      2023-07-05  2022-07-05  2020-07-05  2018-07-05
...           ...             ...         ...         ...         ...
14294  6994825931      2017-10-18  2016-10-18  2014-10-18  2012-10-18
14295  6994826289      2013-12-19  2012-12-19  2010-12-19  2008-12-19
14296  6994826780      2021-10-27  2020-10-27  2018-10-27  2016-10-27
14297  6994826786      2016-01-08  2015-01-08  2013-01-08  2011-01-08
14298  6994826804      2013-10-09  2012-10-09  2010-10-09  2008-10-09

[14299 rows x 5 columns]

In [20]:
pd.read_csv('control_demog.csv')

,person_id,index_age,birth_datetime,gender_source_value,race_source_value,ethnicity_source_value,first_diag_date,1year,3year,5year,race_ethnicity
0,6986700915,73.0,1950-05-27,MALE,WHITE,NOT HISPANIC,2023-09-21,2022-09-21,2020-09-21,2018-09-21,NHW
1,6986702084,21.0,2002-10-02,MALE,WHITE,NOT HISPANIC,2023-12-11,2022-12-11,2020-12-11,2018-12-11,NHW
2,6986704530,26.0,1996-12-10,MALE,UNKNOWN,UNKNOWN,2023-10-03,2022-10-03,2020-10-03,2018-10-03,UNKNOWN
3,6986704851,36.0,1986-11-19,FEMALE,WHITE,NOT HISPANIC,2023-05-31,2022-05-31,2020-05-31,2018-05-31,NHW
4,6986704969,81.0,1942-04-21,MALE,WHITE,NOT HISPANIC,2023-07-05,2022-07-05,2020-07-05,2018-07-05,NHW
...,...,...,...,...,...,...,...,...,...,...,...
14294,6994825931,78.0,1939-03-14,MALE,WHITE,NOT HISPANIC,2017-10-18,2016-10-18,2014-10-18,2012-10-18,NHW
14295,6994826289,91.0,1922-03-09,FEMALE,BLACK,NOT HISPANIC,2013-12-19,2012-12-19,2010-12-19,2008-12-19,NHB
14296,6994826780,13.0,2008-01-20,MALE,BLACK,NOT HISPANIC,2021-10-27,2020-10-27,2018-10-27,2016-10-27,NHB
14297,6994826786,23.0,1992-09-11,FEMALE,BLACK,NOT HISPANIC,2016-01-08,2015-01-08,2013-01-08,2011-01-08,NHB
14298,6994826804,75.0,1937-12-13,FEMALE,BLACK,NOT HISPANIC,2013-10-09,2012-10-09,2010-10-09,2008-10-09,NHB

# 6. get m2

In [49]:
condition_all.to_csv('case_condition.csv', index=False)

In [21]:
condition_all = pd.read_csv('case_condition.csv')

In [22]:
condition_all.shape, condition_all.person_id.nunique()

((4806030, 3), 3370)

In [23]:
baseline = pd.read_csv('case_baseline.csv')

In [24]:
baseline.head()

    person_id first_diag_date       1year       3year       5year
0  6986701922      2023-06-01  2022-06-01  2020-06-01  2018-06-01
1  6986702078      2023-06-06  2022-06-06  2020-06-06  2018-06-06
2  6986703448      2023-05-28  2022-05-28  2020-05-28  2018-05-28
3  6986708252      2023-07-19  2022-07-19  2020-07-19  2018-07-19
4  6986709305      2023-06-10  2022-06-10  2020-06-10  2018-06-10

In [155]:
for year in ['1year', '3year', '5year']:
    al = pd.DataFrame()
    for name, df in tqdm(condition_all.groupby('person_id')):
        df = df.sort_values('condition_start_date')
        df.condition_start_date = pd.to_datetime(df.condition_start_date)
        index_date = baseline[baseline.person_id == name]['first_diag_date'].to_list()[0]
        baseline_date = baseline[baseline.person_id == name][year].to_list()[0]
        feature = df[df.condition_start_date <= baseline_date]
        if len(feature) == 0:
            pass
        else:
            # prediction = df[(df.condition_start_date > baseline_date) & (df.condition_start_date <= index_date) ]
            feature_encounter = feature.groupby(['person_id', 'condition_start_date']).agg({
            'person_id':'first',
            'condition_start_date':'first',
            'condition_source_value':list
                }).reset_index(drop=True)
            m2 = feature_encounter.apply(get_m2, axis=1)
            m2 = pd.concat([pd.DataFrame([m2.iloc[0,0]], columns=['person_id']), pd.DataFrame(m2.iloc[:,3:].max()).T],axis=1)
            al = pd.concat([al, m2])
    print(year,al.shape)
    al.to_csv(f'case_m2_{year}.csv', index=False)

  0%|          | 1/3370 [00:01<1:11:04,  1.27s/it]

NameError: name 'da' is not defined

In [133]:
# calculate score

In [36]:
import re
def get_cci(df_diagnosis_before_index_baseline):
    df_diagnosis_before_index_baseline = df_diagnosis_before_index_baseline.copy()
    diagnosis_len = df_diagnosis_before_index_baseline.shape[1]
    df_diagnosis_before_index_baseline['Myocardial_Infarction'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Myocardial_Infarction)
    df_diagnosis_before_index_baseline['Congestive_heart_failure'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Congestive_heart_failure)
    df_diagnosis_before_index_baseline['Peripheral_vascular_disease'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Peripheral_vascular_disease)
    df_diagnosis_before_index_baseline['Cerebrovascular_disease'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Cerebrovascular_disease)
    df_diagnosis_before_index_baseline['Dementia'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Dementia)
    df_diagnosis_before_index_baseline['Chronic_pulmonary_disease'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Chronic_pulmonary_disease) 
    df_diagnosis_before_index_baseline['Rheumatic_disease'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Rheumatic_disease)
    df_diagnosis_before_index_baseline['Peptic_ulcer_disease'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Peptic_ulcer_disease)
    df_diagnosis_before_index_baseline['Mild_liver_disease'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Mild_liver_disease)
    df_diagnosis_before_index_baseline['Diabetes_without_chronic_complication'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Diabetes_without_chronic_complication)
    df_diagnosis_before_index_baseline['Diabetes_with_chronic_complication'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Diabetes_with_chronic_complication)
    df_diagnosis_before_index_baseline['Hemiplegia_or_paraplegia'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Hemiplegia_or_paraplegia)
    df_diagnosis_before_index_baseline['Renal_disease'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Renal_disease)
    df_diagnosis_before_index_baseline['Cancer'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Cancer)
    df_diagnosis_before_index_baseline['Moderate_or_severe_liver_disease'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Moderate_or_severe_liver_disease)
    df_diagnosis_before_index_baseline['Metastatic_solid_tumor'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_Metastatic_solid_tumor)
    df_diagnosis_before_index_baseline['AIDS_HIV'] = df_diagnosis_before_index_baseline['condition_source_value'].apply(get_AIDS_HIV)
    cci = pd.DataFrame(df_diagnosis_before_index_baseline.iloc[:,diagnosis_len:].any(axis=0).astype(int)).T
    t = cci
    cci_features1 = ['Myocardial_Infarction', 'Congestive_heart_failure', 'Peripheral_vascular_disease', 'Cerebrovascular_disease', 'Chronic_pulmonary_disease', 'Rheumatic_disease', 'Peptic_ulcer_disease', 'Mild_liver_disease', 'Diabetes_without_chronic_complication']
    cci_features2 = ['Diabetes_with_chronic_complication', 'Hemiplegia_or_paraplegia', 'Renal_disease', 'Cancer']
    cci_features3 = ['Metastatic_solid_tumor', 'AIDS_HIV']
    score = t[cci_features1].sum(axis = 1).values[0] + (t[cci_features2].sum(axis = 1).values[0]*2) + (t['Moderate_or_severe_liver_disease'].values[0]*3) + (t[cci_features3].sum(axis = 1).values[0]*6)
    final = pd.DataFrame([df_diagnosis_before_index_baseline.iloc[0,0], score]).T
    final.columns = ['person_id', 'cci_score']
    return final

In [163]:
for year in ['1year', '3year', '5year']:
    al = pd.DataFrame()
    for name, df in tqdm(condition_all.groupby('person_id')):
        df = df.sort_values('condition_start_date')
        df.condition_start_date = pd.to_datetime(df.condition_start_date)
        index_date = baseline[baseline.person_id == name]['first_diag_date'].to_list()[0]
        baseline_date = baseline[baseline.person_id == name][year].to_list()[0]
        feature = df[df.condition_start_date <= baseline_date]
        if len(feature) == 0:
            pass
        else:
            cci = get_cci(feature)
            al = pd.concat([al, cci])
    print(year,al.shape)
    al.to_csv(f'case_cci_{year}.csv', index=False)

100%|██████████| 3370/3370 [03:14<00:00, 17.31it/s]

1year (2241, 2)

100%|██████████| 3370/3370 [01:55<00:00, 29.30it/s]

3year (1483, 2)

100%|██████████| 3370/3370 [01:05<00:00, 51.46it/s]

5year (944, 2)

## control

In [ ]:
root = 'control_all'
person = pd.read_csv(os.path.join(root, 'person.csv'))
condition = pd.read_csv(os.path.join(root, 'condition_occurrence.csv'))[['person_id', 'condition_start_date', 'condition_source_value']]
observation = pd.read_csv(os.path.join(root, 'observation.csv'))[['person_id','observation_date', 'observation_source_value']]
observation.columns = ['person_id', 'condition_start_date', 'condition_source_value']
condition_all = pd.concat([condition, observation])

In [ ]:
condition_all = pd.read_csv('control_condition.csv')
condition_all.shape

In [ ]:
condition_all.shape

(24728084, 3)

In [ ]:
baseline = pd.read_csv('control_baseline.csv')
baseline.shape

(14299, 5)

In [ ]:
al = pd.DataFrame()
for name, df in tqdm(condition_all.groupby('person_id')):
    df = df.sort_values('condition_start_date')
    df.condition_start_date = pd.to_datetime(df.condition_start_date)
    index_date = baseline[baseline.person_id == name]['first_diag_date'].to_list()[0]
    baseline_date = baseline[baseline.person_id == name]['1year'].to_list()[0]
    feature = df[df.condition_start_date <= baseline_date]
    if len(feature) == 0:
        pass
    else:
        # prediction = df[(df.condition_start_date > baseline_date) & (df.condition_start_date <= index_date) ]
        feature_encounter = feature.groupby(['person_id', 'condition_start_date']).agg({
        'person_id':'first',
        'condition_start_date':'first',
        'condition_source_value':list
            }).reset_index(drop=True)
        m2 = feature_encounter.apply(get_m2, axis=1)
        m2 = pd.concat([pd.DataFrame([m2.iloc[0,0]], columns=['person_id']), pd.DataFrame(m2.iloc[:,3:].max()).T],axis=1)
        al = pd.concat([al, m2])

100%|██████████| 14299/14299 [58:24<00:00,  4.08it/s]

In [ ]:
al.to_csv('control_m2.csv', index=False)

In [ ]:
from tqdm import tqdm

In [ ]:
# cci
al = pd.DataFrame()
for name, df in tqdm(condition_all.groupby('person_id')):
    df = df.sort_values('condition_start_date')
    df.condition_start_date = pd.to_datetime(df.condition_start_date)
    index_date = baseline[baseline.person_id == name]['first_diag_date'].to_list()[0]
    baseline_date = baseline[baseline.person_id == name]['1year'].to_list()[0]
    feature = df[df.condition_start_date <= index_date]
    if len(feature) == 0:
        pass
    else:
        cci = get_cci(feature)
        al = pd.concat([al, cci])
print(al.shape)
al.to_csv(f'control_cci.csv', index=False)

100%|██████████| 14299/14299 [21:52<00:00, 10.89it/s]

(14299, 2)

## propensity matching

In [15]:
demog = pd.read_csv('control_demog.csv')
demog['birth_year'] = pd.to_datetime(demog.birth_datetime).dt.year
demog

,person_id,index_age,birth_datetime,gender_source_value,race_source_value,ethnicity_source_value,first_diag_date,1year,3year,5year,race_ethnicity,birth_year
0,6986700915,73.0,1950-05-27,MALE,WHITE,NOT HISPANIC,2023-09-21,2022-09-21,2020-09-21,2018-09-21,NHW,1950
1,6986702084,21.0,2002-10-02,MALE,WHITE,NOT HISPANIC,2023-12-11,2022-12-11,2020-12-11,2018-12-11,NHW,2002
2,6986704530,26.0,1996-12-10,MALE,UNKNOWN,UNKNOWN,2023-10-03,2022-10-03,2020-10-03,2018-10-03,UNKNOWN,1996
3,6986704851,36.0,1986-11-19,FEMALE,WHITE,NOT HISPANIC,2023-05-31,2022-05-31,2020-05-31,2018-05-31,NHW,1986
4,6986704969,81.0,1942-04-21,MALE,WHITE,NOT HISPANIC,2023-07-05,2022-07-05,2020-07-05,2018-07-05,NHW,1942
...,...,...,...,...,...,...,...,...,...,...,...,...
14294,6994825931,78.0,1939-03-14,MALE,WHITE,NOT HISPANIC,2017-10-18,2016-10-18,2014-10-18,2012-10-18,NHW,1939
14295,6994826289,91.0,1922-03-09,FEMALE,BLACK,NOT HISPANIC,2013-12-19,2012-12-19,2010-12-19,2008-12-19,NHB,1922
14296,6994826780,13.0,2008-01-20,MALE,BLACK,NOT HISPANIC,2021-10-27,2020-10-27,2018-10-27,2016-10-27,NHB,2008
14297,6994826786,23.0,1992-09-11,FEMALE,BLACK,NOT HISPANIC,2016-01-08,2015-01-08,2013-01-08,2011-01-08,NHB,1992
14298,6994826804,75.0,1937-12-13,FEMALE,BLACK,NOT HISPANIC,2013-10-09,2012-10-09,2010-10-09,2008-10-09,NHB,1937

In [25]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import NearestNeighbors
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# control
control_cci = pd.read_csv('control_cci.csv')
demog = pd.read_csv('control_demog.csv')
demog['birth_year'] = pd.to_datetime(demog.birth_datetime).dt.year
control = pd.merge(demog, control_cci, on='person_id', how= 'inner')[['person_id', 'birth_year', 'gender_source_value', 'race_ethnicity', 'cci_score']]
control = control[control.gender_source_value != 'UNKNOWN']
gender_encoded = pd.get_dummies(control["gender_source_value"], prefix="gender")
race_encoded = pd.get_dummies(control["race_ethnicity"], prefix="race")
gender_encoded = gender_encoded.astype(int)
race_encoded = race_encoded.astype(int)

control = pd.concat([control, gender_encoded, race_encoded], axis=1)


control.drop(columns=["gender_source_value", "race_ethnicity"], inplace=True)
control['ad'] = 0

for year in ['1year', '3year', '5year']:
    # case
    cci1 = pd.read_csv(f'case_cci_{year}.csv')
    demog = pd.read_csv('case_demog.csv')
    demog['birth_year'] = pd.to_datetime(demog.birth_datetime).dt.year
    keep = pd.merge(demog, cci1, on='person_id', how= 'inner')[['person_id','birth_year', 'gender_source_value', 'race_ethnicity', 'cci_score']]
    gender_encoded = pd.get_dummies(keep["gender_source_value"], prefix="gender")
    race_encoded = pd.get_dummies(keep["race_ethnicity"], prefix="race")
    gender_encoded = gender_encoded.astype(int)
    race_encoded = race_encoded.astype(int)


    df_encoded = pd.concat([keep, gender_encoded, race_encoded], axis=1)

    df_encoded.drop(columns=["gender_source_value", "race_ethnicity"], inplace=True)
    df_encoded['ad'] = 1


    X = pd.concat([control, df_encoded])

    model = LogisticRegression()

    model.fit(X.iloc[:,1:-1], X.iloc[:,-1])

    X1 = X.copy()
    X1['score'] = model.predict_proba(X.iloc[:,1:-1])[:, 1]
    case = X1[X1.ad == 1]
    control1 = X1[X1.ad == 0]
    print('case and control', case.shape, control1.shape)

    
    
    
    all_match = pd.DataFrame()
    match_times = len(control1) // len(case)
    print(control1.shape)
    for i in range(match_times):
        case1 = case.copy()
        while not case1.empty and not control1.empty:
            nn = NearestNeighbors(n_neighbors=1)
            nn.fit(control1[["score"]])  

            distances, indices = nn.kneighbors(case1[["score"]])  
            matched_index = indices.flatten()[0] 


            matched_case = case1.iloc[0]
            matched_control = control1.iloc[matched_index]


            matched_pair = pd.DataFrame({
                "case_id": [matched_case["person_id"]],
                "case_score": [matched_case["score"]],
                "control_id": [matched_control["person_id"]],
                "control_score": [matched_control["score"]],
            })
            all_match = pd.concat([all_match, matched_pair], ignore_index=True)


            control1 = control1.drop(index=matched_index).reset_index(drop=True)


            case1 = case1.iloc[1:].reset_index(drop=True)


    print(all_match.shape)
    print('case uniuqe', all_match.case_id.nunique())
    print('control uniuqe', all_match.control_id.nunique())
    all_match.to_csv(f'match_{year}.csv', index=False)

case and control (2241, 12) (14297, 12)
(14297, 12)
(13446, 4)
case uniuqe 2241
control uniuqe 13445
case and control (1483, 12) (14297, 12)
(14297, 12)
(13347, 4)
case uniuqe 1483
control uniuqe 13346
case and control (944, 12) (14297, 12)
(14297, 12)
(14160, 4)
case uniuqe 944
control uniuqe 14159

In [29]:
condition_all = pd.read_csv('control_condition.csv',index_col=0)
condition_all.shape

(24728084, 3)

In [30]:
# find control index date
from tqdm import tqdm
for year in ['1year','3year','5year']:
    temp = pd.read_csv(f'match_{year}.csv')
    temp.case_id = temp.case_id.astype(int)
    temp.control_id = temp.control_id.astype(int)
    baseline = pd.read_csv('case_baseline.csv')[['person_id', year]]
    baseline.columns = ['case_id', 'case_index_date']
    control = pd.merge(temp, baseline, on='case_id', how='left')[['control_id', 'case_index_date']]
    control.columns = ['person_id', 'case_index_date']
    control_temp = condition_all[condition_all.person_id.isin(control.person_id)]
    all_control_index = pd.DataFrame()
    for name, df in tqdm(control_temp.groupby('person_id')):
        df.condition_start_date = pd.to_datetime(df.condition_start_date)
        df = df.sort_values('condition_start_date')
        flag = control[control.person_id.isin([name])].case_index_date.values[0]
        df['diff'] = (df.condition_start_date - pd.to_datetime(flag)).abs()
        df_sort = df.sort_values('diff')
        left = len(df[df.condition_start_date <= df_sort.head(1).condition_start_date.values[0]])
        df_sort['left_sample'] = left
        all_control_index = pd.concat([all_control_index, df_sort.head(1)])
    all_control_index.to_csv(f'control_reset_index_{year}.csv', index=False)

100%|██████████| 13445/13445 [00:23<00:00, 564.25it/s]
100%|██████████| 13346/13346 [00:23<00:00, 578.20it/s]
100%|██████████| 14159/14159 [00:25<00:00, 560.57it/s]

In [41]:
# now the condition start date of the control reset is the closing encoutner date of its mapped case index date
t1 = pd.read_csv('control_reset_index_1year.csv')
t2 = pd.read_csv('control_reset_index_3year.csv')
t3 = pd.read_csv('control_reset_index_5year.csv')

In [55]:
t1

,person_id,condition_start_date,condition_source_value,diff,left_sample
0,6986700915,2023-09-21,G20.C,961 days,8
1,6986702084,2023-07-11,Marital Status,550 days,24
2,6986704530,2023-06-09,Marital Status,2320 days,7
3,6986704851,2023-05-31,R29.90,688 days,34
4,6986704969,2023-07-05,E03.9,3647 days,13
...,...,...,...,...,...
13440,6994825931,2012-11-15,278.00,318 days,33
13441,6994826289,2012-12-18,V60.9,62 days,2
13442,6994826780,2021-10-06,M62.9,2655 days,12
13443,6994826786,2014-12-24,Marital Status,25 days,318
13444,6994826804,2019-02-26,M54.6,1148 days,354

In [42]:
t1.shape, t2.shape, t3.shape

((13445, 5), (13346, 5), (14159, 5))

In [44]:
ta = pd.concat([t1,t2,t3])

In [45]:
ta.person_id.nunique()

14172

In [46]:
condition_all.shape

(24728084, 3)

In [49]:
for year in ['1year','3year','5year']:
    t = pd.read_csv(f'control_reset_index_{year}.csv')
    condition_temp = condition_all[condition_all.person_id.isin(t.person_id)]
    al = pd.DataFrame()
    for name, df in tqdm(condition_temp.groupby('person_id')):
        df = df.sort_values('condition_start_date')
        df.condition_start_date = pd.to_datetime(df.condition_start_date)
        baseline_date = t[t.person_id == name].condition_start_date.values[0]
        feature = df[df.condition_start_date <= baseline_date]
        if len(feature) == 0:
            pass
        else:
            # prediction = df[(df.condition_start_date > baseline_date) & (df.condition_start_date <= index_date) ]
            feature_encounter = feature.groupby(['person_id', 'condition_start_date']).agg({
            'person_id':'first',
            'condition_start_date':'first',
            'condition_source_value':list
                }).reset_index(drop=True)
            m2 = feature_encounter.apply(get_m2, axis=1)
            m2 = pd.concat([pd.DataFrame([m2.iloc[0,0]], columns=['person_id']), pd.DataFrame(m2.iloc[:,3:].max()).T],axis=1)
            al = pd.concat([al, m2])
    al.to_csv(f'control_m2_{year}.csv', index=False)

100%|██████████| 13445/13445 [18:09<00:00, 12.34it/s]
100%|██████████| 13346/13346 [13:43<00:00, 16.21it/s]
100%|██████████| 14159/14159 [10:11<00:00, 23.14it/s]

# 7. get m3 measurement

In [ ]:
hdl_LOINC = ['772-0','54372-8','2085-9','49130-8','18263-4','14646-4']
glucose_LOINC = ['47622-6','34059-6','27353-2','53553-4']
HbA1C_LOINC = ['41995-2','4548-4','17855-8','4549-2','17856-6','62388-4']
cholesterol_LOINC = ['2093-3','48620-9','14647-2']
bmi_LOINC = ['3038553', '36304833']
dbp = ['55284-4']
mapping = pd.read_csv('loinc2omop.csv',index_col=0)
mapping['Code'] = mapping['Code'].astype(str)

In [68]:
hdl = [str(mapping[mapping.Code.isin([i])].Id.values[0]) for i in hdl_LOINC if not mapping[mapping.Code.isin([i])].empty]
glucose = [str(mapping[mapping.Code.isin([i])].Id.values[0]) for i in glucose_LOINC if not mapping[mapping.Code.isin([i])].empty]
HbA1C = [str(mapping[mapping.Code.isin([i])].Id.values[0]) for i in HbA1C_LOINC if not mapping[mapping.Code.isin([i])].empty]
cholesterol = [str(mapping[mapping.Code.isin([i])].Id.values[0]) for i in cholesterol_LOINC if not mapping[mapping.Code.isin([i])].empty]
# bmi = [str(mapping[mapping.Code.isin([i])].Id.values[0]) for i in bmi_LOINC if not mapping[mapping.Code.isin([i])].empty]
# dbp = [str(mapping[mapping.Code.isin([i])].Id.values[0]) for i in dbp if not mapping[mapping.Code.isin([i])].empty]
height = ['3036277']
weight = ['3025315']
bmi = ['3038553']
dbp = ['4154790']
sbp = ['4152194']

In [926]:
root = 'case_all'

In [927]:

for year in tqdm(['1year', '3year', '5year']):
    measurement = pd.read_csv(os.path.join(root, 'measurement.csv'))
    diag = pd.read_csv(f'case_m2_{year}.csv')
    baseline = pd.read_csv('case_baseline.csv')
    baseline = baseline[baseline.person_id.isin(diag.person_id.to_list())]
    measurement = measurement[measurement.person_id.isin(baseline.person_id.to_list())]    
    print(measurement.shape, measurement.person_id.nunique())
    measurement_encounter = measurement[['person_id', 'measurement_date', 'measurement_concept_id', 'value_as_number', ]]

    m3=[]
    no_encounter_count = 0
    for name, df in measurement_encounter.groupby('person_id'):
        baseline_date = baseline[baseline.person_id == name][year].values[0]
        df = df.sort_values('measurement_date')
        df = df[df.measurement_date <= baseline_date]
        if len(df) == 0:
            no_encounter_count += 1
            pass
        else:
            df.measurement_concept_id = df.measurement_concept_id.astype(str)
            # HDL
            temp = df[df.measurement_concept_id.isin(hdl)]
            if len(temp) == 0:
                hdl_value = np.nan
            else:
                hdl_value = temp.tail(1).value_as_number.values[0]

            # Glucose
            temp = df[df.measurement_concept_id.isin(glucose)]
            if len(temp) == 0:
                glucose_value = np.nan
            else:
                glucose_value = temp.tail(1).value_as_number.values[0]

            # HbA1C
            temp = df[df.measurement_concept_id.isin(HbA1C)]
            if len(temp) == 0:
                HbA1C_value = np.nan
            else:
                HbA1C_value = temp.tail(1).value_as_number.values[0]

            # Cholesterol
            temp = df[df.measurement_concept_id.isin(cholesterol)]
            if len(temp) == 0:
                cholesterol_value = np.nan
            else:
                cholesterol_value = temp.tail(1).value_as_number.values[0]

            # BMI
            temp = df[df.measurement_concept_id.isin(bmi)]
            if len(temp) == 0:
                bmi_value = np.nan
            else:
                bmi_value = temp.tail(1).value_as_number.values[0]
            # height
            temp = df[df.measurement_concept_id.isin(height)]
            if len(temp) == 0:
                height_value = np.nan
            else:
                height_value = temp.tail(1).value_as_number.values[0]
            # weight
            temp = df[df.measurement_concept_id.isin(weight)]
            if len(temp) == 0:
                weight_value = np.nan
            else:
                weight_value = temp.tail(1).value_as_number.values[0]
            # DBP
            temp = df[df.measurement_concept_id.isin(dbp)]
            if len(temp) == 0:
                dbp_value = np.nan
            else:
                dbp_value = temp.tail(1).value_as_number.values[0]
            # sBP
            temp = df[df.measurement_concept_id.isin(sbp)]
            if len(temp) == 0:
                sbp_value = np.nan
            else:
                sbp_value = temp.tail(1).value_as_number.values[0]
            m3.append([name, hdl_value, glucose_value,HbA1C_value,cholesterol_value,bmi_value,height_value,weight_value, dbp_value, sbp_value])
    m3 = pd.DataFrame(m3, columns=['person_id', 'hdl', 'glucose', 'HbA1C', 'cholesterol', 'bmi','height', 'weight', 'dpb', 'sbp'])   
    print(f'there are {no_encounter_count} subjects doesnot have encounters')
    m3.to_csv(f'case_m3_{year}.csv',index=False)

  0%|          | 0/3 [00:00<?, ?it/s]

(10308347, 25) 2239

 33%|███▎      | 1/3 [01:11<02:23, 71.58s/it]

there are 208 subjects doesnot have encounters
(7962074, 25) 1482

 67%|██████▋   | 2/3 [02:12<01:05, 65.52s/it]

there are 146 subjects doesnot have encounters
(5456077, 25) 943

100%|██████████| 3/3 [03:08<00:00, 62.88s/it]

there are 96 subjects doesnot have encounters

In [928]:
# cm and kg
m3

,person_id,hdl,glucose,HbA1C,cholesterol,bmi,height,weight,dpb,sbp
0,6988680239,NaN,NaN,NaN,NaN,NaN,172.72000,52.163082,57.0,157.0
1,6988805508,39.0,NaN,NaN,191.0,NaN,162.56000,63.412163,78.0,132.0
2,6988842190,NaN,NaN,NaN,NaN,NaN,167.64000,72.574720,NaN,NaN
3,6988845112,39.0,197.25,8.5,140.0,NaN,154.94000,79.832190,66.0,128.0
4,6988849604,78.0,NaN,NaN,244.0,NaN,160.02000,67.403780,82.0,143.0
...,...,...,...,...,...,...,...,...,...,...
842,6994770416,60.0,134.11,5.9,204.0,NaN,165.09999,84.005230,69.0,144.0
843,6994789726,NaN,NaN,NaN,NaN,NaN,185.42000,98.883060,76.0,121.0
844,6994802426,NaN,NaN,NaN,NaN,NaN,177.80000,83.007340,74.0,122.0
845,6994813527,NaN,NaN,NaN,NaN,NaN,172.72000,90.718400,105.0,158.0
846,6994816363,NaN,NaN,NaN,NaN,NaN,160.02000,64.410065,71.0,118.0

## control

In [70]:
import numpy as np
root = 'control_all'
measurement = pd.read_csv(os.path.join(root, 'measurement.csv'))
measurement_encounter = measurement[['person_id', 'measurement_date', 'measurement_concept_id', 'value_as_number', ]]

for year in ['1year','3year','5year']:
    t = pd.read_csv(f'control_reset_index_{year}.csv')
    measurement_encounter_temp = measurement_encounter[measurement_encounter.person_id.isin(t.person_id)]
    m3=[]
    no_encounter_count = 0
    for name, df in tqdm(measurement_encounter_temp.groupby('person_id')):
        baseline_date = t[t.person_id == name].condition_start_date.values[0]
        df = df.sort_values('measurement_date')
        df = df[df.measurement_date <= baseline_date]
        if len(df) == 0:
            no_encounter_count += 1
            pass
        else:
            df.measurement_concept_id = df.measurement_concept_id.astype(str)
            # HDL
            temp = df[df.measurement_concept_id.isin(hdl)]
            if len(temp) == 0:
                hdl_value = np.nan
            else:
                hdl_value = temp.tail(1).value_as_number.values[0]

            # Glucose
            temp = df[df.measurement_concept_id.isin(glucose)]
            if len(temp) == 0:
                glucose_value = np.nan
            else:
                glucose_value = temp.tail(1).value_as_number.values[0]

            # HbA1C
            temp = df[df.measurement_concept_id.isin(HbA1C)]
            if len(temp) == 0:
                HbA1C_value = np.nan
            else:
                HbA1C_value = temp.tail(1).value_as_number.values[0]

            # Cholesterol
            temp = df[df.measurement_concept_id.isin(cholesterol)]
            if len(temp) == 0:
                cholesterol_value = np.nan
            else:
                cholesterol_value = temp.tail(1).value_as_number.values[0]

            # BMI
            temp = df[df.measurement_concept_id.isin(bmi)]
            if len(temp) == 0:
                bmi_value = np.nan
            else:
                bmi_value = temp.tail(1).value_as_number.values[0]
            # height
            temp = df[df.measurement_concept_id.isin(height)]
            if len(temp) == 0:
                height_value = np.nan
            else:
                height_value = temp.tail(1).value_as_number.values[0]
            # weight
            temp = df[df.measurement_concept_id.isin(weight)]
            if len(temp) == 0:
                weight_value = np.nan
            else:
                weight_value = temp.tail(1).value_as_number.values[0]
            # DBP
            temp = df[df.measurement_concept_id.isin(dbp)]
            if len(temp) == 0:
                dbp_value = np.nan
            else:
                dbp_value = temp.tail(1).value_as_number.values[0]
            # sBP
            temp = df[df.measurement_concept_id.isin(sbp)]
            if len(temp) == 0:
                sbp_value = np.nan
            else:
                sbp_value = temp.tail(1).value_as_number.values[0]
            m3.append([name, hdl_value, glucose_value,HbA1C_value,cholesterol_value,bmi_value,height_value,weight_value, dbp_value, sbp_value])
    m3 = pd.DataFrame(m3, columns=['person_id', 'hdl', 'glucose', 'HbA1C', 'cholesterol', 'bmi','height', 'weight', 'dpb', 'sbp'])   
    print(f'there are {no_encounter_count} subjects doesnot have encounters')
    m3.to_csv(f'control_m3_{year}.csv',index=False)

100%|██████████| 13384/13384 [00:45<00:00, 291.50it/s]

there are 1677 subjects doesnot have encounters

100%|██████████| 13286/13286 [00:45<00:00, 294.95it/s]

there are 1931 subjects doesnot have encounters

100%|██████████| 14096/14096 [00:44<00:00, 318.10it/s]

there are 2377 subjects doesnot have encounters

In [71]:
m3

,person_id,hdl,glucose,HbA1C,cholesterol,bmi,height,weight,dpb,sbp
0,6986700915,NaN,NaN,NaN,NaN,NaN,175.26000,75.205560,75.0,134.0
1,6986702084,NaN,NaN,NaN,NaN,NaN,179.06999,88.722595,61.0,128.0
2,6986704851,NaN,NaN,NaN,NaN,NaN,162.56000,58.966960,103.0,141.0
3,6986705504,42.0,5.8,5.3,247.0,NaN,193.04000,98.145970,65.0,114.0
4,6986707604,NaN,NaN,NaN,NaN,NaN,176.53000,95.027530,78.0,114.0
...,...,...,...,...,...,...,...,...,...,...
11714,6994823441,NaN,NaN,NaN,NaN,NaN,170.18000,61.234920,86.0,129.0
11715,6994824946,NaN,NaN,NaN,NaN,NaN,125.09500,23.949657,66.0,96.0
11716,6994825931,NaN,NaN,NaN,NaN,NaN,191.77000,160.798370,68.0,124.0
11717,6994826289,NaN,NaN,NaN,NaN,NaN,162.56000,79.699000,60.0,146.0
11718,6994826786,NaN,NaN,NaN,NaN,NaN,162.56000,58.966960,68.0,121.0

# 8. get M5

In [72]:
import re
def get_m5(row):
    text = str(row.text)
    # moca
    moca_list = [
        r"moca total score[ ]*total score .*?:.*?(\d{1,2})",
        r"(\d{1,2}/30)(?!/).*on the .*moca",
        r"(?:moca|montreal cognitive assessment) = ?(\d{1,2})(?!/)",
        r"(?:moca|montreal cognitive assessment) (?!education).*?(\d{1,2}/30)(?!/)",
        r"(?:moca|montreal cognitive assessment) (?!education).*?(\d{1,2} out of 30)(?!/)",
        r"(?:moca|montreal cognitive assessment):(?!education).*?(\d{1,2}/30)(?!/)",
        r"MOCA\) (?:[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2} ){1}(?!\d).*?orientation.*?total score.*?(?:out of 30)\) ?((\d{1,2} ){1})",
        r"MOCA\) (?:[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2} ){2}(?!\d).*?orientation.*?total score.*?(?:out of 30)\) ?((\d{1,2} ){2})",
        r"MOCA\) (?:[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2} ){3}(?!\d).*?orientation.*?total score.*?(?:out of 30)\) ?((\d{1,2} ){3})",
        r"MOCA\) (?:[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2} ){4}(?!\d).*?orientation.*?total score.*?(?:out of 30)\) ?((\d{1,2} ){4})",
        r"MOCA\) (?:[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2} ){5}(?!\d).*?orientation.*?total score.*?(?:out of 30)\) ?((\d{1,2} ){5})"
    ]

    # The `val` specifying the group to extract
    val = "group(1)"

    # Apply each regex and extract the score
    moca_values = []
    for expression in moca_list:
        match = re.search(expression, text, re.IGNORECASE)
        if match:
            score = eval(f"match.{val}")  # Dynamically extract group(1)
            moca_values.append(score)
    row['moca'] = moca_values

    # Define the list of regex patterns for MMSE
    mmse_list = [
        r"(?:mmse|mini-mental status exam) (?!=).*?(\d{1,2}/30)",
        r"(?:mmse|mini-mental status exam) ?((\d{1,2}/30 ){1,})",
        r"(?:mmse|mini-mental status exam): .*?((\d{1,2}/30 ){1,})",
        r"mmse = ?(\d{2})(?!/)",
        r"(?:mmse|mini-mental status exam) = ?(\d{1,2}/30)",
        r"mini mental status exam .* ?(\d{1,2}/30)",
        r"(\d{1,2}/30) on mmse",
        r"mmse\) (?:[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2} ){1}(?!\d).*?orientation.*?total score.*?((\d{1,2} ){1})",
        r"mmse\) (?:[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2} ){2}(?!\d).*?orientation.*?total score.*?((\d{1,2} ){2})",
        r"mmse\) (?:[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2} ){3}(?!\d).*?orientation.*?total score.*?((\d{1,2} ){3})",
        r"mmse\) (?:[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2} ){4}(?!\d).*?orientation.*?total score.*?((\d{1,2} ){4})",
        r"mmse\) (?:[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2} ){5}(?!\d).*?orientation.*?total score.*?((\d{1,2} ){5})",
        r"mmse\) (?![ ]{0,}folstein)(?!([0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2})).*?total score.*?(\d{1,2})",
        r"mmse: ?(\d{1,2} )",
        r"mini mental state exam: ?(\d{1,2})",
        r"total mmse ?(\d{1,2})",
        r"(?:mini-mental status|mini-mental state examination) .*?(\d{1,2}) out of 30"
    ]


    # List to store all matched values
    mmse_values = []

    # Apply each regex and extract the score
    for expression in mmse_list:
        match = re.search(expression, text, re.IGNORECASE)
        if match:
            score = eval(f"match.{val}")  # Extract group(1) dynamically
            mmse_values.append(score)
            
    row['mmse'] = mmse_values
    # apoe
    apoe_list = [
        r"(?:apoe|apolipoprotein e).*?(\d{1}/\d{1})",
        r"(\d{1}/\d{1}) apoe genotype"
    ]


    # List to store all matched values
    apoe_values = []

    # Apply each regex and extract the value
    for expression in apoe_list:
        match = re.search(expression, text, re.IGNORECASE)
        if match:
            score = eval(f"match.{val}")  # Extract group(1) dynamically
            apoe_values.append(score)
            
    row['apoe'] = apoe_values
    # drs
    drs_list = [
        r"overall cdr ?([0-9]\.[0-9]|[0-9])",
        r"clinical dementia rating scale category of[ ]{1,}?([0-9]\.[0-9]|[0-9])",
        r"clinical dementia rating scale\):([0-9])",
        r"cdr total = ([0-9])",
        r"clinical dementia rating scale.*sum of boxes = ([0-9])",
        r"clinical dementia rating scale.*overall cdr = ([0-9])",
        r"clinical dementia rating scale is ([0-9])"
    ]

    # List to store all matched values
    drs_values = []

    # Apply each regex and extract the value
    for expression in drs_list:
        match = re.search(expression, text, re.IGNORECASE)
        if match:
            score = eval(f"match.{val}")  # Extract group(1) dynamically
            drs_values.append(score)
            
    row['drs'] = drs_values
    # cog
    cog_list = [
        r"mini cog.*?(?:[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2}).*negative screen ?(\d{1})",
        r"mini cog:[ ]{0,}?(\d{1}/5|\d{1} )",
        r"(?:mini-cog|mini cog score)[ ]{1,}?(\d{1}/5|\d{1} )"
    ]

    # List to store all matched values
    cog_values = []

    # Apply each regex and extract the value
    for expression in cog_list:
        match = re.search(expression, text, re.IGNORECASE)
        if match:
            score = eval(f"match.{val}")  # Extract group(1) dynamically
            cog_values.append(score)

    row['cog'] = cog_values
    # Define the list of regex patterns for GDS
    gds_list = [
        r"gds-(\d{1,2})",
        r"geriatric depression scale score (?:.*): ?(\d{1,2})",
        r"(?:geriatric depression scale|gds)[ ]{1,}(?:= ){0,}?(\d{1,2}/[ ]{0,}\d{1,2}|\d{1,2})",
        r"(?:geriatric depression scale|gds),[ ]{1,}?(\d{1,2}/\d{1,2})",
        r"(?:geriatric depression scale|gds) ?(\d{1,2})"
    ]


    # List to store all matched values
    gds_values = []

    # Apply each regex and extract the value
    for expression in gds_list:
        match = re.search(expression, text, re.IGNORECASE)
        if match:
            score = eval(f"match.{val}")  # Extract group(1) dynamically
            gds_values.append(score)
    row['gds'] = gds_values
    return row

In [73]:
def process_row(df):
    columns_to_check = ['moca', 'mmse', 'apoe', 'drs', 'cog', 'gds']
    processed = {"person_id": df["person_id"].iloc[-1]}  # Keep the last person_id
    for col in columns_to_check:
        if col == "apoe":  # Special case for 'apoe'
            # Record 1 if there is any value in the column, otherwise 0
            processed[col] = 1 if df[col].apply(lambda x: isinstance(x, list) and len(x) > 0).any() else 0
        else:
            # For other columns, get the last non-empty list
            non_empty_values = df[col].apply(lambda x: x if isinstance(x, list) and len(x) > 0 else np.nan)
            if non_empty_values.notna().any():
                processed[col] = non_empty_values[non_empty_values.notna()].iloc[-1]
            else:
                processed[col] = np.nan
    return processed

In [313]:

root = '/orange/bianjiang/huyu/2024-10-02/Notes_For_Regex/Regex'
for folder in os.listdir(root):
    print('@'*20)
    print(folder)
    all_g_notes = pd.DataFrame()
    if folder.startswith('.'):
        continue
    else:
        for n in os.listdir(os.path.join(root, folder)):
            # print(notes)
            if n.startswith('.'):
                pass
            else:
                temp = pd.read_csv(os.path.join(root, folder, n))
                all_g_notes = pd.concat([all_g_notes, temp])
    all_g_notes.columns = ['_index', '_id', '_score', 'text',
       'note_id']
    all_g_notes.note_id = all_g_notes.note_id.astype(str)
    notes.note_id = notes.note_id.astype(str)
    meg = pd.merge(notes, all_g_notes, on = 'note_id' ,how = 'inner')
    print('notes count from key words', len(all_g_notes))
    # print('notes count from all case patients', len(notes))
    # print('notes that showed on both file', len(meg))
    no = round((len(meg)/len(notes))*100,5)
    p = meg.person_id.nunique()
    pp = round((p/9050)*100,5)
    print(f'number and percentage of notes contain keywords: {len(meg)} {no}%')
    print(f'number and percentage of patients who have keywords: {p} {pp}%')

@@@@@@@@@@@@@@@@@@@@
Montreal Cognitive Assessment (MoCA)
notes count from key words 83946
number and percentage of notes contain keywords: 339 0.55293%
number and percentage of patients who have keywords: 189 2.0884%
@@@@@@@@@@@@@@@@@@@@
Global Deterioration Scale (GDS)
notes count from key words 7037
number and percentage of notes contain keywords: 19 0.03099%
number and percentage of patients who have keywords: 19 0.20994%
@@@@@@@@@@@@@@@@@@@@
Mini_Cog
notes count from key words 16640
number and percentage of notes contain keywords: 50 0.08155%
number and percentage of patients who have keywords: 25 0.27624%
@@@@@@@@@@@@@@@@@@@@
Mini-mental state (MMSE)
notes count from key words 51446
number and percentage of notes contain keywords: 181 0.29522%
number and percentage of patients who have keywords: 145 1.60221%
@@@@@@@@@@@@@@@@@@@@
Clinical Dementia Rating (CDR) or CDR-Sum of Boxes (CDR-SB)
notes count from key words 698
number and percentage of notes contain keywords: 1 0.00163%
number and percentage of patients who have keywords: 1 0.01105%
@@@@@@@@@@@@@@@@@@@@
APOE
notes count from key words 13986
number and percentage of notes contain keywords: 53 0.08645%
number and percentage of patients who have keywords: 32 0.35359%
@@@@@@@@@@@@@@@@@@@@
.ipynb_checkpoints
@@@@@@@@@@@@@@@@@@@@
Functional Activities Questionnaire (FAQ)
notes count from key words 11972
number and percentage of notes contain keywords: 32 0.05219%
number and percentage of patients who have keywords: 27 0.29834%

In [937]:
root = 'case_all'
notes = pd.read_csv(os.path.join(root, 'all_notes.csv'),index_col=0)
notes.columns = ['note_id', 'text', 'person_id', 'EncounterDate']

In [508]:
notes.person_id.nunique()

2333

In [509]:
notes.shape

(15418, 4)

In [421]:
root = '/orange/bianjiang/huyu/2024-10-02/Notes_For_Regex/Regex'
all_g_notes = pd.DataFrame()
for folder in os.listdir(root):
    print('@'*20)
    print(folder)
    if folder.startswith('.'):
        continue
    else:
        for n in os.listdir(os.path.join(root, folder)):
            # print(notes)
            if n.startswith('.'):
                pass
            else:
                temp = pd.read_csv(os.path.join(root, folder, n))
                all_g_notes = pd.concat([all_g_notes, temp])
all_g_notes.columns = ['_index', '_id', '_score', 'text',
       'note_id']
all_g_notes.note_id = all_g_notes.note_id.astype(str)
notes.note_id = notes.note_id.astype(str)

@@@@@@@@@@@@@@@@@@@@
Montreal Cognitive Assessment (MoCA)
@@@@@@@@@@@@@@@@@@@@
Global Deterioration Scale (GDS)
@@@@@@@@@@@@@@@@@@@@
Mini_Cog
@@@@@@@@@@@@@@@@@@@@
Mini-mental state (MMSE)
@@@@@@@@@@@@@@@@@@@@
Clinical Dementia Rating (CDR) or CDR-Sum of Boxes (CDR-SB)
@@@@@@@@@@@@@@@@@@@@
APOE
@@@@@@@@@@@@@@@@@@@@
.ipynb_checkpoints
@@@@@@@@@@@@@@@@@@@@
Functional Activities Questionnaire (FAQ)

In [422]:
all_g_notes.shape

(185725, 5)

In [423]:
notes.note_id = notes.note_id.astype(str)

In [424]:
merged_note = pd.merge(notes, all_g_notes, on = 'note_id' ,how = 'inner')

In [425]:
merged_note.shape

(184, 8)

In [427]:
location = pd.read_csv('case_location.csv')
location

,person_id,condition_start_date,birth_datetime,condition_source_value,outcome_mci,outcome_ad,outcome_control,time_period,outcome_sum,index_age,first_diag_date,site
0,6986752842,2023-05-06,1952-01-25,"['F05', 'G30.9', 'G30.9', 'E78.5', 'F02.80', '...",1,1,0,0.0,mci + ad,71.0,2023-05-06,jax
1,6986998921,2022-05-10,1960-04-11,"['N18.9', 'I25.10', 'R45.851', 'E11.9', 'J45.9...",1,1,0,0.0,mci + ad,62.0,2023-02-25,jax
2,6987021399,2022-10-05,1947-03-26,"['R60.0', 'E03.9', 'E03.9', 'R41.3', 'R41.3', ...",1,1,0,10.0,mci + ad,75.0,2023-01-19,jax
3,6987060229,2022-11-01,1937-12-21,"['I10', 'I10', 'Zipcode', 'SMOKING STATUS', '3...",1,1,0,1.0,mci + ad,85.0,2023-12-19,jax
4,6987083318,2023-01-09,1932-06-05,"['R55', 'R55', 'G30.9', 'F02.80', 'F02.80', 'G...",1,1,0,1.0,mci + ad,90.0,2022-11-28,jax
...,...,...,...,...,...,...,...,...,...,...,...,...
3365,6994758548,2017-06-19,1930-12-19,"['G30.9', 'G30.9', 'F02.80', 'S51.001A', 'F02....",0,1,0,11.0,ad,86.0,2017-06-19,gnv
3366,6994804666,2013-11-08,1937-12-04,"['591', '592.1', '592.0', '591', '591', '331.0...",0,1,0,10.0,ad,75.0,2013-11-08,gnv
3367,6994807332,2012-04-05,1932-08-03,"['331.0', '331.0', 'Payer', 'SMOKING STATUS', ...",0,1,0,9.0,ad,79.0,2012-04-05,gnv
3368,6994821246,2013-05-11,1930-03-07,"['788.30', '788.30', '788.30', '331.0', '788.3...",0,1,0,9.0,ad,83.0,2013-05-11,gnv
3369,6994823175,2018-07-13,1943-08-20,"['E03.9', 'R05', 'J44.9', 'F02.81', 'F02.80', ...",0,1,0,6.0,ad,74.0,2018-07-13,gnv

In [428]:
merged_note = pd.merge(merged_note, location[['person_id', 'site']], on ='person_id', how='left')
merged_note

,note_id,text_x,person_id,EncounterDate,_index,_id,_score,text_y,site
0,7535715537,"""Psychiatry Evaluation and History & Physical ...",6994802402,2016-04-03,adrd_patient_clinical_notes,irPJH5QBI2Jva8IG6awx,2.453339,"""Psychiatry Evaluation and History & Physical ...",jax
1,7702400133,"""[**LOCATION_INSTITUTE**] [**LOCATION_INSTITUT...",6993446729,2017-12-06,adrd_patient_clinical_notes,ErXJH5QBI2Jva8IG-QTs,12.271278,"""[**LOCATION_INSTITUTE**] [**LOCATION_INSTITUT...",jax
2,7688839159,"""Subjective: [**NAME**] is a [**AGE**] y.o. ma...",6993729922,2017-09-26,adrd_patient_clinical_notes,OLXJH5QBI2Jva8IG-iVL,8.037272,"""Subjective: [**NAME**] is a [**AGE**] y.o. ma...",gnv
3,7688839159,"""Subjective: [**NAME**] is a [**AGE**] y.o. ma...",6993729922,2017-09-26,adrd_patient_clinical_notes,OLXJH5QBI2Jva8IG-iVL,8.037272,"""Subjective: [**NAME**] is a [**AGE**] y.o. ma...",gnv
4,6883202312,"""[**LOCATION_INSTITUTE**] Department of Neurol...",6991212440,2015-07-15,adrd_patient_clinical_notes,97rKH5QBI2Jva8IGLzwt,4.193295,"""[**LOCATION_INSTITUTE**] Department of Neurol...",jax
...,...,...,...,...,...,...,...,...,...
179,7596671443,"""Attending Subsequent Hospital Care CPT Code: ...",6990644635,2016-11-03,adrd_patient_clinical_notes,lKvWH5QBI2Jva8IGTA_h,4.886403,"""Attending Subsequent Hospital Care CPT Code: ...",gnv
180,7596671443,"""Attending Subsequent Hospital Care CPT Code: ...",6990644635,2016-11-03,adrd_patient_clinical_notes,lKvWH5QBI2Jva8IGTA_h,4.668375,"""Attending Subsequent Hospital Care CPT Code: ...",gnv
181,7596671443,"""Attending Subsequent Hospital Care CPT Code: ...",6990644635,2016-11-03,adrd_patient_clinical_notes,lKvWH5QBI2Jva8IGTA_h,4.886403,"""Attending Subsequent Hospital Care CPT Code: ...",gnv
182,7240718300,"""Subjective: [**NAME**] is a [**AGE**] y.o. fe...",6994806930,2013-06-26,adrd_patient_clinical_notes,w63WH5QBI2Jva8IGZrTj,5.396349,"""Subjective: [**NAME**] is a [**AGE**] y.o. fe...",jax
183,7240718300,"""Subjective: [**NAME**] is a [**AGE**] y.o. fe...",6994806930,2013-06-26,adrd_patient_clinical_notes,w63WH5QBI2Jva8IGZrTj,5.396349,"""Subjective: [**NAME**] is a [**AGE**] y.o. fe...",jax

In [510]:
notes

,note_id,text,person_id,EncounterDate
Unnamed: 0,,,,
26,7323540247,SPOK sent to wound nurse regarding suprapubic ...,6991460042,2019-04-23
28,7171867338,[**NAME**] 5/15/2014 2:00 PM Office Visit Desc...,6994789726,2014-03-05
29,7171867338,[**NAME**] 5/15/2014 2:00 PM Office Visit Desc...,6994789726,2014-03-05
36,6944613852,Report given to [**NAME**].,6992362091,2015-12-15
57,7250540049,Physical Therapy Orthopedic Daily Treatment Da...,6990971696,2014-06-25
...,...,...,...,...
158802,6857169257,Problem: Impaired bed mobility (PT) Goal: PT L...,6992221394,2015-05-17
158818,7283172720,"""August 26, 2019 Dear [**NAME**] MRN: [**ID**]...",6991548906,2018-12-10
158847,7478330132,"""Patient Encounter - Office Visit Subjective: ...",6991629462,2019-10-10
158850,7148398197,"""Interval History and Physical Note Admission ...",6990675354,2013-12-13
158873,7590030625,Medication Reconciliation Department of Pharma...,6992801866,2016-09-22

In [511]:
# get baseline year notes
for year in ['1year','3year','5year']:
    diag = pd.read_csv(f'case_m2_{year}.csv')
    baseline = pd.read_csv('case_baseline.csv')
    baseline = pd.merge(diag, baseline, on='person_id', how='inner')
    merged_note = notes[notes.person_id.isin(baseline.person_id.to_list())]
    m5 = pd.DataFrame()
    baseline_note = pd.DataFrame()
    for name,df in merged_note.groupby('person_id'):
        merged_note = notes[notes.person_id.isin(baseline.person_id.to_list())]
        baseline_date = baseline[baseline.person_id == name][year].values[0]
        df = df.sort_values('EncounterDate')
        df = df[df.EncounterDate <= baseline_date]
        if len(df) == 0:
            pass
        else:
            baseline_note = pd.concat([baseline_note, df])
    baseline_note.to_csv(f'case_all/notes_{year}.csv', index=False)

In [142]:
root = 'control_all'
notes = pd.read_csv(os.path.join(root, 'all_notes.csv')).iloc[:,1:]

In [144]:
root = 'control_all'
notes = pd.read_csv(os.path.join(root, 'all_notes.csv')).iloc[:,1:]
notes.columns = ['note_id', 'text', 'person_id', 'EncounterDate']

for year in ['1year','3year','5year']:
    t = pd.read_csv(f'control_reset_index_{year}.csv')
    notes_temp = notes[notes.person_id.isin(t.person_id)]
    m5 = pd.DataFrame()
    baseline_note = pd.DataFrame()
    for name,df in tqdm(notes_temp.groupby('person_id')):
        # merged_note = notes[notes.person_id.isin(baseline.person_id.to_list())]
        baseline_date = t[t.person_id == name].condition_start_date.values[0]
        df = df.sort_values('EncounterDate')
        df = df[df.EncounterDate <= baseline_date]
        if len(df) == 0:
            pass
        else:    
            baseline_note = pd.concat([baseline_note, df])
    baseline_note.to_csv(f'control_all/notes_{year}.csv', index=False)

100%|██████████| 8578/8578 [00:12<00:00, 687.10it/s]
100%|██████████| 8514/8514 [00:11<00:00, 743.27it/s]
100%|██████████| 8970/8970 [00:11<00:00, 795.46it/s]

In [515]:
pd.read_csv('case_all/notes_3year.csv')

,note_id,text,person_id,EncounterDate
0,7300476243,Department of Surgery Division of Pediatric Su...,6988556464,2019-02-06
1,7716884412,Request/Reason for call: [**NAME**] with [**LO...,6988577236,2018-02-09
2,7346249151,"Spoke to HOP, I told him I would see Dr. A in ...",6988599931,2019-05-20
3,7348556640,Attestation I saw and evaluated the patient. I...,6988599931,2019-07-03
4,7362070117,Occupational Therapy Treatment Note Start Time...,6988599931,2019-07-11
...,...,...,...,...
3434,6898427677,Pts dialysis clinic states that pt was febrile...,6994802426,2015-08-17
3435,6948877926,[**NAME**] About My Hospitalization I was admi...,6994802426,2015-12-07
3436,6722477042,"""January 5, 2015 [**NAME**], MD [**LOCATION_ST...",6994816363,2012-09-04
3437,6868034591,Tell [**NAME**] I saw the message from 11/25 r...,6994823175,2015-05-27
3438,7010112929,History Chief Complaint Patient presents with ...,6994824439,2012-02-28

In [806]:
ca = pd.read_csv('case_all/notes_1year.csv')

In [807]:
cc = pd.read_csv('control_all/all_notes.csv', index_col=0)
cc.columns = ca.columns

In [808]:
test = pd.concat([cc, ca])

In [809]:
test.shape

(67257, 4)

In [810]:
test.head()

,note_id,text,person_id,EncounterDate
1,7781562747,"----- Message from [**NAME**], MD, PhD sent at...",6993127432,2018-07-24
2,7338155709,"""Department of Anesthesiology Pre-operative Ev...",6993669779,2019-04-29
4,7004095222,Department of Radiology Division of Interventi...,6992285958,2012-01-14
6,7242850361,"""Chief Complaint: follow up Patient Active Pro...",6993976728,2012-06-15
7,7242850361,"""Chief Complaint: follow up Patient Active Pro...",6993976728,2012-06-15

In [813]:
diag = pd.read_csv(f'case_m2_1year.csv')
baseline = pd.read_csv('case_baseline.csv')
baseline = pd.merge(diag, baseline, on='person_id', how='inner')
merged_note = test[test.person_id.isin(baseline.person_id.to_list())]
m5 = pd.DataFrame()
for name,df in merged_note.groupby('person_id'):
        merged_note = notes[notes.person_id.isin(baseline.person_id.to_list())]
        baseline_date = baseline[baseline.person_id == name][year].values[0]
        df = df.sort_values('EncounterDate')
        df = df[df.EncounterDate <= baseline_date]
        if len(df) == 0:
            pass
        else:    
            temp = df.apply(get_m5, axis=1)[['person_id', 'moca', 'mmse', 'apoe', 'drs', 'cog', 'gds']]
            temp = pd.DataFrame([process_row(temp)])
            m5 = pd.concat([m5, temp])

In [816]:
m5

     person_id moca mmse  apoe  drs  cog  gds
0   6988845112  NaN  NaN     0  NaN  NaN  NaN
0   6989031592  NaN  NaN     0  NaN  NaN  NaN
0   6989094961  NaN  NaN     0  NaN  NaN  NaN
0   6989170827  NaN  NaN     0  NaN  NaN  NaN
0   6989269271  NaN  NaN     0  NaN  NaN  NaN
..         ...  ...  ...   ...  ...  ...  ...
0   6994756779  NaN  NaN     0  NaN  NaN  NaN
0   6994758548  NaN  NaN     0  NaN  NaN  NaN
0   6994759242  NaN  NaN     0  NaN  NaN  NaN
0   6994770416  NaN  NaN     0  NaN  NaN  NaN
0   6994802426  NaN  NaN     0  NaN  NaN  NaN

[506 rows x 7 columns]

In [815]:
m5.columns

Index(['person_id', 'moca', 'mmse', 'apoe', 'drs', 'cog', 'gds'], dtype='object')

In [817]:

al_notes = pd.DataFrame()
for i in ['moca', 'mmse', 'apoe', 'drs', 'cog', 'gds']:
    
    if i == 'apoe':
        missing_rate = round((len(m5[m5[i].isna()])/len(m5))*100,2)
        count = m5[i].sum()
        count_on_person = round((count/len(m5))*100,5)
        count_on_notes = round((count/len(notes))*100,5)
        row = pd.DataFrame([i, count, count_on_person, count_on_notes]).T
        row.columns = ['notes', 'count', 'person has notes on all person percentage', 'notes count on all notes percentage',]
        row['all'] = row['count'].astype(str) + ' (' + row['person has notes on all person percentage'].astype(str)+'%)'+ ' (' +str(missing_rate)+'%)'
        al_notes = pd.concat([al_notes, row])
        
    else:
        missing_rate = round((len(m5[m5[i].isna()])/len(m5))*100,2)
        count = len(m5[i][~m5[i].isna()])
        count_on_person = round((count/len(m5))*100,5)
        count_on_notes = round((count/len(notes))*100,5)
        row = pd.DataFrame([i, count, count_on_person, count_on_notes]).T
        
        row.columns = ['notes', 'count', 'person has notes on all person percentage', 'notes count on all notes percentage',]
        row['all'] = row['count'].astype(str) + ' (' + row['person has notes on all person percentage'].astype(str)+'%)'+ ' (' +str(missing_rate)+'%)'
        al_notes = pd.concat([al_notes, row])

In [818]:
al_notes

,notes,count,person has notes on all person percentage,notes count on all notes percentage,all
0,moca,2,0.39526,0.01297,2 (0.39526%) (99.6%)
0,mmse,4,0.79051,0.02594,4 (0.79051%) (99.21%)
0,apoe,1,0.19763,0.00649,1 (0.19763%) (0.0%)
0,drs,0,0.0,0.0,0 (0.0%) (100.0%)
0,cog,0,0.0,0.0,0 (0.0%) (100.0%)
0,gds,0,0.0,0.0,0 (0.0%) (100.0%)

In [938]:
for year in ['1year','3year','5year']:
    diag = pd.read_csv(f'case_m2_{year}.csv')
    baseline = pd.read_csv('case_baseline.csv')
    baseline = pd.merge(diag, baseline, on='person_id', how='inner')
    merged_note = notes[notes.person_id.isin(baseline.person_id.to_list())]
    m5 = pd.DataFrame()
    for name,df in merged_note.groupby('person_id'):
        merged_note = notes[notes.person_id.isin(baseline.person_id.to_list())]
        baseline_date = baseline[baseline.person_id == name][year].values[0]
        df = df.sort_values('EncounterDate')
        df = df[df.EncounterDate <= baseline_date]
        if len(df) == 0:
            pass
        else:    
            temp = df.apply(get_m5, axis=1)[['person_id', 'moca', 'mmse', 'apoe', 'drs', 'cog', 'gds']]
            temp = pd.DataFrame([process_row(temp)])
            m5 = pd.concat([m5, temp])
    m5.to_csv(f'case_m5_{year}.csv', index=False)

In [336]:
al_notes = pd.DataFrame()
for i in ['moca', 'mmse', 'apoe', 'drs', 'cog', 'gds']:
    if i == 'apoe':
        count = m5[i].sum()
        count_on_person = round((count/len(m5))*100,5)
        count_on_notes = round((count/len(notes))*100,5)
        row = pd.DataFrame([i, count, count_on_person, count_on_notes]).T
        row.columns = ['notes', 'count', 'person has notes on all person percentage', 'notes count on all notes percentage',]
        al_notes = pd.concat([al_notes, row])
        
    else:
        count = len(m5[i][~m5[i].isna()])
        count_on_person = round((count/len(m5))*100,5)
        count_on_notes = round((count/len(notes))*100,5)
        row = pd.DataFrame([i, count, count_on_person, count_on_notes]).T
        row.columns = ['notes', 'count', 'person has notes on all person percentage', 'notes count on all notes percentage',]
        al_notes = pd.concat([al_notes, row])

In [337]:
al_notes.to_csv('case_1year_notes_jax.csv',index=False)

In [116]:
for i in ['moca', 'mmse', 'apoe', 'drs', 'cog', 'gds']:
    if i == 'apoe':
        count = m5[i].sum()
        print(i,': ', count, round((count/len(m5))*100,5),'%', round((count/len(notes))*100,5),'%')
    else:
        count = len(m5[i][~m5[i].isna()])
        print(i,': ',count, round((count/len(m5))*100,5),'%', round((count/len(notes))*100,5),'%')

moca :  12 30.76923 % 0.18335 %
mmse :  10 25.64103 % 0.15279 %
apoe :  3 7.69231 % 0.04584 %
drs :  0 0.0 % 0.0 %
cog :  1 2.5641 % 0.01528 %
gds :  2 5.12821 % 0.03056 %

## control

In [74]:
root = 'control_all'
notes = pd.read_csv(os.path.join(root, 'all_notes.csv')).iloc[:,2:]
notes.columns = ['text', 'person_id', 'EncounterDate']

for year in ['1year','3year','5year']:
    t = pd.read_csv(f'control_reset_index_{year}.csv')
    notes_temp = notes[notes.person_id.isin(t.person_id)]
    m5 = pd.DataFrame()
    for name,df in tqdm(notes_temp.groupby('person_id')):
        # merged_note = notes[notes.person_id.isin(baseline.person_id.to_list())]
        baseline_date = t[t.person_id == name].condition_start_date.values[0]
        df = df.sort_values('EncounterDate')
        df = df[df.EncounterDate <= baseline_date]
        if len(df) == 0:
            pass
        else:    
            temp = df.apply(get_m5, axis=1)[['person_id', 'moca', 'mmse', 'apoe', 'drs', 'cog', 'gds']]
            temp = pd.DataFrame([process_row(temp)])
            m5 = pd.concat([m5, temp])
    m5.to_csv(f'control_m5_{year}.csv', index=False)

100%|██████████| 8721/8721 [00:55<00:00, 157.86it/s]
100%|██████████| 8693/8693 [00:45<00:00, 189.67it/s]
100%|██████████| 8977/8977 [00:35<00:00, 249.73it/s]

# 9. get M4

In [76]:
NSAIDs_ingredients = ['16689','16695','17387','1029','19847','140587','237162','3355','23687','24605','307296','24830','4331','4502','5640','5781','28198','6142','35827','28876',
                      '20890','257844','41493','7258','32526','32613','279950','8160','8356','34769','232158','10237','10255','37790','618442','38377','278567','39994']
statins_ingredients = ['83367','596723','41127','6472','861634','42463','301542','36567']
anticholinergics_ingredients = ['596', '620', '704', '722', '89013', '784649', '1223', '1292', '1424', '1767', '1998', '2002', '20220', '2101', '20610', '2356', '2400', '2409', '2403', '2541', 
                                '2578', '21232', '2597', '2598', '2353', '2626', '2670', '2977', '21949', '3013', '136198', '3247', '3322', '3361', '3407', '3444', '3498', '3521', '3541', '3638',
                                '4278', '4337', '4440', '4493', '4496', '4501', '42355', '4603', '1546438', '5093', '5470', '5553', '153970', '73178', '5691', '6057', '6468', '28889', '6475', '6676',
                                '107770', '6754', '6845', '89785', '15996', '7052', '7417', '42319', '7531', '61381', '7715', '32624', '32675', '7804', '32937', '8076', '8331', '8640', '8704', '8745',
                                '8761', '8886', '8896', '51272', '9068', '9143', '35636', '9601', '10355', '10502', '10510', '57258', '119565', '10689', '10737', '10763', '10800', '10811', '38685', '10834', '236778', '11289', '115698']
hormone_ingredients = ['1441391','2397','3368','3390','4083','4094','4099','4103','4124','34625','38260','1441386','2397',
                       '4083','4100','4099','214549','4103','33747','4124','1370971','34119','9066','253166','618365']
antihypertensives_ingredients = ['802519','214223','1008801','852897','1009015','1033889','901212','729455','151195','1235143','214287','214288','214317','284628','214357',
                                 '214536','352375','261415','608424','214617','214618','214619','214620','214621','214622','817496','214623','261417','284636','214626','1656339',
                                 '214866','2599','5033','40114','5470','40138','28863','1442132','6673','6876','6877','266604','6984','7476','1439816','136411','358263','358274',
                                 '1523','75207','2599','3118','62174','3327','3409','49276','5036','40114','5470','5784','6131','1442132','6673','235829','6876','266604','6984','30257',
                                 '7476','7930','33717','8629','9259','9260','55679','1439816','10828','39230','17767','404773','3443','4316','33910','7396','7417','7426','7435','11170',
                                 '17767','1436','233603','3443','4316','4327','4648','33910','28382','135056','6390','29275','39879','83213','7396','7417','53692','7426','7435','7441','8050','11170']
benzodiazepines_ingredients = ['596','2356','21241','2598','2353','3322','4077','4501','6470','6960','7781','35185','10355','10767']
PPI_ingredients = ['816346','283742','17128','7646','40790','114979']
rxnorm = pd.read_csv('omop2rxnorm2.csv',index_col=0)[['Id', 'Code']]

In [77]:
# NSAIDs
NSAIDs = [str(rxnorm[rxnorm.Code.isin([i])].Id.values[0]) for i in NSAIDs_ingredients if not rxnorm[rxnorm.Code.isin([i])].empty]

# Statins
statins = [str(rxnorm[rxnorm.Code.isin([i])].Id.values[0]) for i in statins_ingredients if not rxnorm[rxnorm.Code.isin([i])].empty]

# Anticholinergics
anticholinergics = [str(rxnorm[rxnorm.Code.isin([i])].Id.values[0]) for i in anticholinergics_ingredients if not rxnorm[rxnorm.Code.isin([i])].empty]

# Hormones
hormones = [str(rxnorm[rxnorm.Code.isin([i])].Id.values[0]) for i in hormone_ingredients if not rxnorm[rxnorm.Code.isin([i])].empty]

# Antihypertensives
antihypertensives = [str(rxnorm[rxnorm.Code.isin([i])].Id.values[0]) for i in antihypertensives_ingredients if not rxnorm[rxnorm.Code.isin([i])].empty]

# Benzodiazepines
benzodiazepines = [str(rxnorm[rxnorm.Code.isin([i])].Id.values[0]) for i in benzodiazepines_ingredients if not rxnorm[rxnorm.Code.isin([i])].empty]

# PPI
PPI = [str(rxnorm[rxnorm.Code.isin([i])].Id.values[0]) for i in PPI_ingredients if not rxnorm[rxnorm.Code.isin([i])].empty]

In [78]:
# NSAIDs
NSAIDs = pd.read_csv('nsaid.csv',index_col=0)[['Id']].astype(str).Id.to_list()
# Statins
statins = pd.read_csv('statins.csv',index_col=0)[['Id']].astype(str).Id.to_list()

# Anticholinergics
anticholinergics = pd.read_csv('anticholinergics.csv',index_col=0)[['Id']].astype(str).Id.to_list()

# Hormones
hormones = pd.read_csv('hormone.csv',index_col=0)[['Id']].astype(str).Id.to_list()

# Antihypertensives
antihypertensives = pd.read_csv('antihypertensives.csv',index_col=0)[['Id']].astype(str).Id.to_list()

# Benzodiazepines
benzodiazepines = pd.read_csv('benzodiazepines.csv',index_col=0)[['Id']].astype(str).Id.to_list()

# PPI
PPI = pd.read_csv('ppi.csv',index_col=0)[['Id']].astype(str).Id.to_list()

In [79]:
def get_m4(row):
    all_list = [str(i) for i in row.drug_concept_id]  
    if len(set(all_list).intersection(set(NSAIDs))) != 0:
        row['NSAIDs'] = 1
    else:
        row['NSAIDs'] = 0

    if len(set(all_list).intersection(set(statins))) != 0:
        row['statins'] = 1
    else:
        row['statins'] = 0

    if len(set(all_list).intersection(set(anticholinergics))) != 0:
        row['anticholinergics'] = 1
    else:
        row['anticholinergics'] = 0

    if len(set(all_list).intersection(set(hormones))) != 0:
        row['hormones'] = 1
    else:
        row['hormones'] = 0

    if len(set(all_list).intersection(set(antihypertensives))) != 0:
        row['antihypertensives'] = 1
    else:
        row['antihypertensives'] = 0

    if len(set(all_list).intersection(set(benzodiazepines))) != 0:
        row['benzodiazepines'] = 1
    else:
        row['benzodiazepines'] = 0

    if len(set(all_list).intersection(set(PPI))) != 0:
        row['PPI'] = 1
    else:
        row['PPI'] = 0
    
    return row

In [482]:
root = 'case_all'
drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))

/scratch/local/56132859/ipykernel_284924/3010702396.py:2: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))

In [500]:
for year in ['1year','3year','5year']:
    diag = pd.read_csv(f'case_m2_{year}.csv')
    baseline = pd.read_csv('case_baseline.csv')
    baseline = pd.merge(diag, baseline, on='person_id', how='inner')
    drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
    drug = drug[drug.person_id.isin(baseline.person_id.to_list())]
    all_drug = pd.DataFrame()
    for name,df in drug.groupby('person_id'):
        baseline_date = baseline[baseline.person_id == name][year].values[0]
        df = df.sort_values('drug_exposure_start_date')
        df = df[df.drug_exposure_start_date	 <= baseline_date]
        all_drug = pd.concat([all_drug, df])
    drug_encounter = all_drug[['person_id', 'drug_exposure_start_date', 'drug_concept_id']].groupby(['person_id', 'drug_exposure_start_date']).agg({
        'person_id':'first',
        'drug_exposure_start_date':'first',
        'drug_concept_id':list
            }).reset_index(drop=True)
    temp = drug_encounter.apply(get_m4, axis=1)
    m4 = pd.DataFrame()
    for name, df in temp.groupby('person_id'):
        df = pd.concat([pd.DataFrame([df.iloc[0,0]], columns=['person_id']), pd.DataFrame(df.iloc[:,3:].max()).T],axis=1)
        m4 = pd.concat([m4, df])
    m4.to_csv(f'case_m4_{year}.csv', index=False)

/scratch/local/56132859/ipykernel_284924/1953078492.py:5: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
/scratch/local/56132859/ipykernel_284924/1953078492.py:5: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
/scratch/local/56132859/ipykernel_284924/1953078492.py:5: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))

In [501]:
m4.sum()

person_id            4971678726569
NSAIDs                         252
statins                        346
anticholinergics               512
hormones                        46
antihypertensives              263
benzodiazepines                239
PPI                            231
dtype: int64

In [102]:
root = 'case_all'
drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
drug_encounter = drug[['person_id', 'drug_exposure_start_date', 'drug_concept_id']].groupby(['person_id', 'drug_exposure_start_date']).agg({
    'person_id':'first',
    'drug_exposure_start_date':'first',
    'drug_concept_id':list
        }).reset_index(drop=True)
temp = drug_encounter.apply(get_m4, axis=1)
m4 = pd.DataFrame()
for name, df in temp.groupby('person_id'):
    df = pd.concat([pd.DataFrame([df.iloc[0,0]], columns=['person_id']), pd.DataFrame(df.iloc[:,3:].max()).T],axis=1)
    m4 = pd.concat([m4, df])

In [105]:
drug.person_id.nunique(),drug_encounter.shape

(1029, (82536, 3))

In [103]:
m4.sum()

person_id            7194785843777
NSAIDs                         619
statins                        723
anticholinergics               974
hormones                       100
antihypertensives              707
benzodiazepines                688
PPI                            576
dtype: int64

## control

In [80]:
root = 'control_all'
drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
for year in ['1year','3year','5year']:
    t = pd.read_csv(f'control_reset_index_{year}.csv')
    drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
    drug_encounter_temp = drug[drug.person_id.isin(t.person_id)]
    all_drug = pd.DataFrame()
    for name,df in tqdm(drug_encounter_temp.groupby('person_id')):
        baseline_date = t[t.person_id == name].condition_start_date.values[0]
        df = df.sort_values('drug_exposure_start_date')
        df = df[df.drug_exposure_start_date	 <= baseline_date]
        all_drug = pd.concat([all_drug, df])
    drug_encounter = all_drug[['person_id', 'drug_exposure_start_date', 'drug_concept_id']].groupby(['person_id', 'drug_exposure_start_date']).agg({
        'person_id':'first',
        'drug_exposure_start_date':'first',
        'drug_concept_id':list
            }).reset_index(drop=True)
    temp = drug_encounter.apply(get_m4, axis=1)
    m4 = pd.DataFrame()
    for name, df in temp.groupby('person_id'):
        df = pd.concat([pd.DataFrame([df.iloc[0,0]], columns=['person_id']), pd.DataFrame(df.iloc[:,3:].max()).T],axis=1)
        m4 = pd.concat([m4, df])    
    m4.to_csv(f'control_m4_{year}.csv', index=False)

/var/folders/qd/p70m9c454hb0dg39fvsykmjrxprw2j/T/ipykernel_4048/2649130639.py:2: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
/var/folders/qd/p70m9c454hb0dg39fvsykmjrxprw2j/T/ipykernel_4048/2649130639.py:5: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
100%|██████████| 13216/13216 [14:35<00:00, 15.10it/s]
/var/folders/qd/p70m9c454hb0dg39fvsykmjrxprw2j/T/ipykernel_4048/2649130639.py:5: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
100%|██████████| 13116/13116 [10:41<00:00, 20.45it/s]
/var/folders/qd/p70m9c454hb0dg39fvsykmjrxprw2j/T/ipykernel_4048/2649130639.py:5: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
100%|██████████| 13891/13891 [07:49<00:00, 29.59it/s]

In [105]:
root = 'control_all'
drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
for year in ['1year','3year','5year']:
    t = pd.read_csv(f'control_reset_index_{year}.csv')
    drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
    drug_encounter_temp = drug[drug.person_id.isin(t.person_id)]
    all_drug = pd.DataFrame()
    for name,df in tqdm(drug_encounter_temp.groupby('person_id')):
        baseline_date = t[t.person_id == name].condition_start_date.values[0]
        df = df.sort_values('drug_exposure_start_date')
        df = df[df.drug_exposure_start_date	 <= baseline_date]
        all_drug = pd.concat([all_drug, df])
    drug_encounter = all_drug[['person_id', 'drug_exposure_start_date', 'drug_concept_id']].groupby(['person_id', 'drug_exposure_start_date']).agg({
        'person_id':'first',
        'drug_exposure_start_date':'first',
        'drug_concept_id':list
            }).reset_index(drop=True)
    temp = drug_encounter.apply(get_m4, axis=1)
    m4 = pd.DataFrame()
    for name, df in temp.groupby('person_id'):
        df = pd.concat([pd.DataFrame([df.iloc[0,0]], columns=['person_id']), pd.DataFrame(df.iloc[:,3:].max()).T],axis=1)
        m4 = pd.concat([m4, df])    
    m4.to_csv(f'control_m4_{year}.csv', index=False)

/scratch/local/56262023/ipykernel_353087/2649130639.py:2: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
/scratch/local/56262023/ipykernel_353087/2649130639.py:5: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
100%|██████████| 13209/13209 [31:57<00:00,  6.89it/s]
/scratch/local/56262023/ipykernel_353087/2649130639.py:5: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
100%|██████████| 13113/13113 [24:58<00:00,  8.75it/s]
/scratch/local/56262023/ipykernel_353087/2649130639.py:5: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
100%|██████████| 13896/13896 [18:47<00:00, 12.32it/s]

In [81]:
m4.sum()

person_id            71049494335815
NSAIDs                         3421
statins                        2170
anticholinergics               6418
hormones                        796
antihypertensives              2415
benzodiazepines                3274
PPI                            2432
dtype: int64

In [502]:
root = 'control_all'
drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
drug_encounter = drug[['person_id', 'drug_exposure_start_date', 'drug_concept_id']].groupby(['person_id', 'drug_exposure_start_date']).agg({
    'person_id':'first',
    'drug_exposure_start_date':'first',
    'drug_concept_id':list
        }).reset_index(drop=True)
temp = drug_encounter.apply(get_m4, axis=1)
m4 = pd.DataFrame()
for name, df in tqdm(temp.groupby('person_id')):
    df = pd.concat([pd.DataFrame([df.iloc[0,0]], columns=['person_id']), pd.DataFrame(df.iloc[:,3:].max()).T],axis=1)
    m4 = pd.concat([m4, df])

/scratch/local/56132859/ipykernel_284924/3936102872.py:2: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  drug = pd.read_csv(os.path.join(root, 'drug_exposure.csv'))
100%|██████████| 14024/14024 [00:17<00:00, 815.71it/s]

In [503]:
m4.sum()

person_id            98048632878919
NSAIDs                         8613
statins                        4716
anticholinergics              12042
hormones                       2161
antihypertensives              6401
benzodiazepines                7781
PPI                            5742
dtype: int64

In [108]:
m4.sum()

person_id            98048632878919
NSAIDs                         8613
statins                        4716
anticholinergics              12042
hormones                       2161
antihypertensives              6401
benzodiazepines                7781
PPI                            5742
dtype: int64

In [504]:
m4.to_csv('control_m4.csv', index=False)

# 10. concat

In [85]:
def get_bmi(row):
    if pd.isna(row.weight) or pd.isna(row.height):
        row.bmi = np.nan
    else:
        row.bmi = round(row.weight / ((row.height / 100) ** 2),2)
    return row

In [84]:
cols = ['person_id', 'index_age', 'birth_datetime', 'gender_source_value',
       'race_source_value', 'ethnicity_source_value', 'first_diag_date(ad)',
       'race_ethnicity', 'site',
        'obesity', 'diabetes', 'hyperlipidemiam', 'hypertension', 'heart disease',
       'stroke', 'depression', 'anxiety', 'concussion', 'sleep_disorder',
       'periodontitis', 'smoke', 'alcohol_abuse',
        'high-density lipoprotein', 'glucose', 'HbA1C',
       'cholesterol', 'bmi', 'systolic/diastolic blood pressure', 'NSAIDs', 'statins', 'anticholinergics',
       'hormone replacement therapies', 'antihypertensives', 'benzodiazepines', 'proton pump inhibitors', 'Montreal Cognitive Assessment (MoCA)',
       'Mini-mental state (MMSE)', 'Apolipoprotein E (APOE)', 'Dementia Rating Scale (DRS)', 'Mini-Cog', 'Global Deterioration Scale (GDS)']

In [86]:
import os
save = 'file_to_share'
os.makedirs(save, exist_ok=True)

In [111]:
control = pd.read_csv('control_demog.csv')
temp = pd.read_csv('control_reset_index_1year.csv')[['person_id', 'condition_start_date']]
control = pd.merge(temp, control, on='person_id',how='inner')
control['index_age'] = ((pd.to_datetime(control.condition_start_date) - pd.to_datetime(control.birth_datetime)).dt.days/365.25).round()
control = control.drop(columns=['condition_start_date'])
control

,person_id,index_age,birth_datetime,gender_source_value,race_source_value,ethnicity_source_value,first_diag_date,1year,3year,5year,race_ethnicity
0,6986700915,73.0,1950-05-27,MALE,WHITE,NOT HISPANIC,2023-09-21,2022-09-21,2020-09-21,2018-09-21,NHW
1,6986702084,21.0,2002-10-02,MALE,WHITE,NOT HISPANIC,2023-12-11,2022-12-11,2020-12-11,2018-12-11,NHW
2,6986704530,26.0,1996-12-10,MALE,UNKNOWN,UNKNOWN,2023-10-03,2022-10-03,2020-10-03,2018-10-03,UNKNOWN
3,6986704851,37.0,1986-11-19,FEMALE,WHITE,NOT HISPANIC,2023-05-31,2022-05-31,2020-05-31,2018-05-31,NHW
4,6986704969,81.0,1942-04-21,MALE,WHITE,NOT HISPANIC,2023-07-05,2022-07-05,2020-07-05,2018-07-05,NHW
...,...,...,...,...,...,...,...,...,...,...,...
13440,6994825931,74.0,1939-03-14,MALE,WHITE,NOT HISPANIC,2017-10-18,2016-10-18,2014-10-18,2012-10-18,NHW
13441,6994826289,91.0,1922-03-09,FEMALE,BLACK,NOT HISPANIC,2013-12-19,2012-12-19,2010-12-19,2008-12-19,NHB
13442,6994826780,14.0,2008-01-20,MALE,BLACK,NOT HISPANIC,2021-10-27,2020-10-27,2018-10-27,2016-10-27,NHB
13443,6994826786,22.0,1992-09-11,FEMALE,BLACK,NOT HISPANIC,2016-01-08,2015-01-08,2013-01-08,2011-01-08,NHB
13444,6994826804,81.0,1937-12-13,FEMALE,BLACK,NOT HISPANIC,2013-10-09,2012-10-09,2010-10-09,2008-10-09,NHB

In [115]:
# concat case control
for year in ['1year', '3year', '5year']:
   #  control
   control = pd.read_csv('control_demog.csv')
   temp = pd.read_csv(f'control_reset_index_{year}.csv')[['person_id', 'condition_start_date']]
   control = pd.merge(temp, control, on='person_id',how='inner')
   control['index_age'] = ((pd.to_datetime(control.condition_start_date) - pd.to_datetime(control.birth_datetime)).dt.days/365.25).round()
   control = control.drop(columns=['condition_start_date'])
   control = control[['person_id', 'index_age', 'birth_datetime', 'gender_source_value',
      'race_source_value', 'ethnicity_source_value', 'first_diag_date','race_ethnicity']]
   location = pd.read_csv('control_location.csv')[['person_id', 'outcome_sum', 'site']]
   control = pd.merge(control, location,on='person_id',how='inner')
   m2 = pd.read_csv(f'control_m2_{year}.csv')
   control = pd.merge(control, m2,on='person_id',how='inner')
   m3 = pd.read_csv(f'control_m3_{year}.csv')
   control = pd.merge(control, m3,on='person_id',how='left')
   m4 = pd.read_csv(f'control_m4_{year}.csv')
   control = pd.merge(control, m4,on='person_id',how='left')
   m5 = pd.read_csv(f'control_m5_{year}.csv')
   control = pd.merge(control, m5,on='person_id',how='left')
   print(control.shape)
   match = pd.read_csv(f'match_{year}.csv')

   #  case
   case = pd.read_csv('case_demog.csv')[['person_id', 'index_age', 'birth_datetime', 'gender_source_value',
      'race_source_value', 'ethnicity_source_value', 'first_diag_date','race_ethnicity']]
   location = pd.read_csv('case_location.csv')[['person_id', 'outcome_sum', 'site']]
   case = pd.merge(case, location,on='person_id',how='inner')
   print(case.shape)
   m2 = pd.read_csv(f'case_m2_{year}.csv')
   case = pd.merge(case, m2,on='person_id',how='inner')
   m3 = pd.read_csv(f'case_m3_{year}.csv')
   case = pd.merge(case, m3,on='person_id',how='left')
   m4 = pd.read_csv(f'case_m4_{year}.csv')
   case = pd.merge(case, m4,on='person_id',how='left')
   m5 = pd.read_csv(f'case_m5_{year}.csv')
   case = pd.merge(case, m5,on='person_id',how='left')
   print(case.shape)

   match = match[match.case_id.isin(case.person_id.to_list())]
   match.control_id.astype(int)
   all_year = pd.concat([case, control[control.person_id.isin(match.control_id.astype(int))]])
   all_year= all_year.apply(get_bmi, axis=1)
   all_year = all_year.drop(columns=['height', 'weight'])
   print(all_year.shape)
   print('*'*50)
   all_year.to_csv(f'{save}/case_control_{year}.csv', index=False)

(13445, 45)
(3370, 10)
(2241, 45)
(15686, 43)
**************************************************
(13346, 45)
(3370, 10)
(1483, 45)
(14829, 43)
**************************************************
(14159, 45)
(3370, 10)
(944, 45)
(15103, 43)
**************************************************